<?php
return [
    '1' => ['code' => '1', 'name' => '逍遥游', 'nameFull' => '逍遥游', 'brief' => '庄子第一篇', 'keyword' => ''],
    '2' => ['code' => '2', 'name' => '齐物论', 'nameFull' => '齐物论', 'brief' => '庄子第二篇', 'keyword' => ''],
    '3' => ['code' => '3', 'name' => '养生主', 'nameFull' => '养生主', 'brief' => '庄子第三篇', 'keyword' => ''],
    '4' => ['code' => '4', 'name' => '人间世', 'nameFull' => '人间世', 'brief' => '庄子第四篇', 'keyword' => ''],
    '5' => ['code' => '5', 'name' => '德充符', 'nameFull' => '德充符', 'brief' => '庄子第五篇', 'keyword' => ''],
    '6' => ['code' => '6', 'name' => '大宗师', 'nameFull' => '大宗师', 'brief' => '庄子第九篇', 'keyword' => ''],
    '7' => ['code' => '7', 'name' => '应帝王', 'nameFull' => '应帝王', 'brief' => '庄子第九篇', 'keyword' => ''],
    '8' => ['code' => '8', 'name' => '骈拇', 'nameFull' => '胼拇', 'brief' => '庄子第九篇', 'keyword' => ''],
    '9' => ['code' => '9', 'name' => '马蹄', 'nameFull' => '马蹄', 'brief' => '庄子第九篇', 'keyword' => ''],
    '10' => ['code' => '10', 'name' => '胠箧', 'nameFull' => '胠箧', 'brief' => '庄子第十篇', 'keyword' => ''],
    '11' => ['code' => '11', 'name' => '在宥', 'nameFull' => '在宥', 'brief' => '庄子第十一篇', 'keyword' => ''],
    '12' => ['code' => '12', 'name' => '天地', 'nameFull' => '天地', 'brief' => '庄子第十二篇', 'keyword' => ''],
    '13' => ['code' => '13', 'name' => '天道', 'nameFull' => '在宥', 'brief' => '庄子第十三篇', 'keyword' => ''],
    '14' => ['code' => '14', 'name' => '天运', 'nameFull' => '天运', 'brief' => '庄子第十四篇', 'keyword' => ''],
    '15' => ['code' => '15', 'name' => '刻意', 'nameFull' => '刻意', 'brief' => '庄子第十五篇', 'keyword' => ''],
    '16' => ['code' => '16', 'name' => '缮性', 'nameFull' => '缮性', 'brief' => '庄子第十六篇', 'keyword' => ''],
    '17' => ['code' => '17', 'name' => '秋水', 'nameFull' => '秋水', 'brief' => '庄子第十七篇', 'keyword' => ''],
    '18' => ['code' => '18', 'name' => '至乐', 'nameFull' => '至乐', 'brief' => '庄子第十八篇', 'keyword' => ''],
    '19' => ['code' => '19', 'name' => '达生', 'nameFull' => '达生', 'brief' => '庄子第十八篇', 'keyword' => ''],
    '20' => ['code' => '20', 'name' => '山木', 'nameFull' => '山木', 'brief' => '庄子第二十篇', 'keyword' => ''],
    '21' => ['code' => '21', 'name' => '田子方', 'nameFull' => '田子方', 'brief' => '庄子第二十一篇', 'keyword' => ''],
    '22' => ['code' => '22', 'name' => '知北游', 'nameFull' => '知北游', 'brief' => '庄子第二十二篇', 'keyword' => ''],
    '23' => ['code' => '23', 'name' => '庚桑楚', 'nameFull' => '庚桑楚', 'brief' => '庄子第二十三篇', 'keyword' => ''],
    '24' => ['code' => '24', 'name' => '徐无鬼', 'nameFull' => '徐无鬼', 'brief' => '庄子第二十四篇', 'keyword' => ''],
    '25' => ['code' => '25', 'name' => '则阳', 'nameFull' => '则阳', 'brief' => '庄子第二十五篇', 'keyword' => ''],
    '26' => ['code' => '26', 'name' => '外物', 'nameFull' => '外物', 'brief' => '庄子第二十六篇', 'keyword' => ''],
    '27' => ['code' => '27', 'name' => '寓言', 'nameFull' => '寓言', 'brief' => '庄子第二十七篇', 'keyword' => ''],
    '28' => ['code' => '28', 'name' => '让王', 'nameFull' => '让王', 'brief' => '庄子第二十八篇', 'keyword' => ''],
    '29' => ['code' => '29', 'name' => '盗跖', 'nameFull' => '盗跖', 'brief' => '庄子第二十九篇', 'keyword' => ''],
    '30' => ['code' => '30', 'name' => '说剑', 'nameFull' => '说剑', 'brief' => '庄子第三十篇', 'keyword' => ''],
    '31' => ['code' => '31', 'name' => '渔父', 'nameFull' => '渔夫', 'brief' => '庄子第三十一篇', 'keyword' => ''],
    '32' => ['code' => '32', 'name' => '列御寇', 'nameFull' => '列御寇', 'brief' => '庄子第三十二篇', 'keyword' => ''],
    '33' => ['code' => '33', 'name' => '天下', 'nameFull' => '天下', 'brief' => '庄子第三十三篇', 'keyword' => ''],
];
