    <a name="anchor9"></a>
    <div class="custom_border lindBox">
        <div class="custom_head">
            <div class="custom_title">
                <h2>美国总统上任时年龄</h2>
                <!--Contents of this file are Copyright 2006-2017, Xixik.com.--></div>
            <div class="custom_totop">
                <a href="#top" target="_self">
                    <div class="ico"></div>
                </a>
            </div>
        </div>
        <div class="custom_content">
            <div class='content_text'>
                <table border="1" bordercolor="#cccccc" cellpadding="2" cellspacing="1" style="text-align: left; margin: auto; width:90%">
                    <tbody>
                        <tr>
                            <th>任次</th>
                            <th>
                                <a style="color:#000" title="美国总统" href="http://m.114.xixik.com/us-president/">美国总统</a></th>
                            <th>就任总统时年纪</th></tr>
                        <tr>
                            <td>1</td>
                            <td>乔治·华盛顿</td>
                            <td>57岁67天</td></tr>
                        <tr>
                            <td>2</td>
                            <td>约翰·亚当斯</td>
                            <td>61岁125天</td></tr>
                        <tr>
                            <td>3</td>
                            <td>托马斯·杰斐逊</td>
                            <td>57岁325天</td></tr>
                        <tr>
                            <td>4</td>
                            <td>詹姆斯·麦迪逊</td>
                            <td>57岁353天</td></tr>
                        <tr>
                            <td>5</td>
                            <td>詹姆斯·门罗</td>
                            <td>58岁310天</td></tr>
                        <tr>
                            <td>6</td>
                            <td>约翰·昆西·亚当斯</td>
                            <td>57岁236天</td></tr>
                        <tr>
                            <td>7</td>
                            <td>安德鲁·杰克逊</td>
                            <td>61岁354天</td></tr>
                        <tr>
                            <td>8</td>
                            <td>马丁·范布伦</td>
                            <td>54岁89天</td></tr>
                        <tr>
                            <td>9</td>
                            <td>威廉·亨利·哈里森</td>
                            <td>68岁23天</td></tr>
                        <tr>
                            <td>10</td>
                            <td>约翰·泰勒</td>
                            <td>51岁6天</td></tr>
                        <tr>
                            <td>11</td>
                            <td>詹姆斯·诺克斯·波尔克</td>
                            <td>49岁122天</td></tr>
                        <tr>
                            <td>12</td>
                            <td>札卡里·泰勒</td>
                            <td>64岁100天</td></tr>
                        <tr>
                            <td>13</td>
                            <td>米勒德·菲尔莫尔</td>
                            <td>50岁183天</td></tr>
                        <tr>
                            <td>14</td>
                            <td>富兰克林·皮尔斯</td>
                            <td>48岁101天</td></tr>
                        <tr>
                            <td>15</td>
                            <td>詹姆斯·布坎南</td>
                            <td>65岁315天</td></tr>
                        <tr>
                            <td>16</td>
                            <td>阿布拉罕·林肯</td>
                            <td>52岁20天</td></tr>
                        <tr>
                            <td>17</td>
                            <td>安德鲁·约翰逊</td>
                            <td>56岁107天</td></tr>
                        <tr>
                            <td>18</td>
                            <td>尤利塞斯·辛普森·格兰特</td>
                            <td>46岁311天</td></tr>
                        <tr>
                            <td>19</td>
                            <td>拉特福德·伯查德·海斯</td>
                            <td>54岁151天</td></tr>
                        <tr>
                            <td>20</td>
                            <td>詹姆斯·阿布拉姆·加菲尔德</td>
                            <td>49岁105天</td></tr>
                        <tr>
                            <td>21</td>
                            <td>切斯特·阿兰·阿瑟</td>
                            <td>51岁349天</td></tr>
                        <tr>
                            <td>22</td>
                            <td>史蒂芬·格罗弗·克利夫兰</td>
                            <td>47岁351天</td></tr>
                        <tr>
                            <td>23</td>
                            <td>本杰明·哈里森</td>
                            <td>55岁196天</td></tr>
                        <tr>
                            <td>24</td>
                            <td>史蒂芬·格罗弗·克利夫兰</td>
                            <td>55岁351天</td></tr>
                        <tr>
                            <td>25</td>
                            <td>威廉·麦金利</td>
                            <td>54岁34天</td></tr>
                        <tr>
                            <td>26</td>
                            <td>西奥多·罗斯福</td>
                            <td>42岁322天</td></tr>
                        <tr>
                            <td>27</td>
                            <td>威廉·霍华德·塔夫特</td>
                            <td>51岁170天</td></tr>
                        <tr>
                            <td>28</td>
                            <td>托马斯·伍德罗·威尔逊</td>
                            <td>56岁66天</td></tr>
                        <tr>
                            <td>29</td>
                            <td>沃伦·加马利尔·哈丁</td>
                            <td>55岁122天</td></tr>
                        <tr>
                            <td>30</td>
                            <td>卡尔文·约翰·柯立芝</td>
                            <td>51岁29天</td></tr>
                        <tr>
                            <td>31</td>
                            <td>赫伯特·克拉克·胡佛</td>
                            <td>54岁206天</td></tr>
                        <tr>
                            <td>32</td>
                            <td>富兰克林·德拉诺·罗斯福</td>
                            <td>51岁33天</td></tr>
                        <tr>
                            <td>33</td>
                            <td>哈里.S.杜鲁门</td>
                            <td>60岁339天</td></tr>
                        <tr>
                            <td>34</td>
                            <td>德怀特·大卫·艾森豪威尔</td>
                            <td>62岁98天</td></tr>
                        <tr>
                            <td>35</td>
                            <td>约翰·菲茨杰拉德·肯尼迪</td>
                            <td>43岁236天</td></tr>
                        <tr>
                            <td>36</td>
                            <td>林登·贝因斯·约翰逊</td>
                            <td>55岁87天</td></tr>
                        <tr>
                            <td>37</td>
                            <td>理查德·米卢斯·尼克松</td>
                            <td>56岁11天</td></tr>
                        <tr>
                            <td>38</td>
                            <td>杰拉德·鲁道夫·福特</td>
                            <td>61岁26天</td></tr>
                        <tr>
                            <td>39</td>
                            <td>吉米·厄尔·卡特</td>
                            <td>52岁111天</td></tr>
                        <tr>
                            <td>40</td>
                            <td>罗纳德·威尔逊·里根</td>
                            <td>69岁349天</td></tr>
                        <tr>
                            <td>41</td>
                            <td>乔治·赫伯特·沃克·布什</td>
                            <td>64岁222天</td></tr>
                        <tr>
                            <td>42</td>
                            <td>威廉·杰弗森·
                                <a style="color:#000" title="克林顿" href="http://m.114.xixik.com/us-president/bill-clinton/">克林顿</a></td>
                            <td>46岁154天</td></tr>
                        <tr>
                            <td>43</td>
                            <td>乔治·沃克·布什</td>
                            <td>54岁198天</td></tr>
                        <tr>
                            <td>44</td>
                            <td>巴拉克·侯赛因·
                                <a style="color:#000" title="奥巴马" href="http://m.114.xixik.com/us-president/obama/">奥巴马</a>二世</td>
                            <td>47岁169天</td></tr>
                        <tr>
                            <td>45</td>
                            <td>唐纳德·
                                <a style="color:#000" title="特朗普" href="http://m.114.xixik.com/us-president/trump/">特朗普</a></td>
                            <td>70岁220天</td></tr>
                        <tr>
                            <td>46</td>
                            <td>乔·
                                <a style="color:#000" title="拜登" href="http://m.114.xixik.com/us-president/biden/">拜登</a></td>
                            <td>78岁？天</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
