cp migrations/daodejing/2.php migrations/daodejing/30.php
cp migrations/daodejing/2.php migrations/daodejing/31.php
cp migrations/daodejing/2.php migrations/daodejing/32.php
cp migrations/daodejing/2.php migrations/daodejing/33.php
cp migrations/daodejing/2.php migrations/daodejing/34.php
cp migrations/daodejing/2.php migrations/daodejing/35.php
cp migrations/daodejing/2.php migrations/daodejing/36.php
cp migrations/daodejing/2.php migrations/daodejing/37.php
cp migrations/daodejing/2.php migrations/daodejing/38.php
cp migrations/daodejing/3.php migrations/daodejing/39.php
