<?php
return [
    'name' => '',
    'brief' => '',
    'chapters' => [
        [
            'content' => [
                '逢纷',
                '伊伯庸之末胄兮，谅皇直之屈原。',
                '云余肇祖于高阳兮，惟楚怀之婵连。',
                '原生受命于贞节兮，鸿永路有嘉名。',
                '齐名字于天地兮，并光明于列星。',
                '吸精粹而吐氛浊兮，横邪世而不取容。',
                '行叩诚而不阿兮，遂见排而逢谗。',
                '后听虚而黜实兮，不吾理而顺情。',
                '肠愤悁而含怒兮，志迁蹇而左倾。',
                '心戃慌其不我与兮，躬速速其不吾亲。',
                '辞灵修而陨志兮，吟泽畔之江滨。',
                '椒桂罗以颠覆兮，有竭信而归诚。',
                '谗夫蔼蔼而漫著兮，曷其不舒予情？',
                '始结言于庙堂兮，信中涂而叛之。',
                '怀兰蕙与衡芷兮，行中野而散之。',
                '声哀哀而怀高丘兮，心愁愁而思旧邦。',
                '愿承闲而自恃兮，径淫曀而道壅。',
                '颜霉黧以沮败兮，精越裂而衰耄。',
                '裳襜襜而含风兮，衣纳纳而掩露。',
                '赴江湘之湍流兮，顺波凑而下降。',
                '徐徘徊于山阿兮，飘风来之洶洶。',
                '驰余车兮玄石，步余马兮洞庭。',
                '平明发兮苍梧，夕投宿兮石城。',
                '芙蓉盖而菱华车兮，紫贝阙而玉堂。',
                '薜荔饰而陆离荐兮，鱼鳞衣而白蜺裳。',
                '登逢龙而下陨兮，违故都之漫漫。',
                '思南郢之旧俗兮，肠一夕而九运。',
                '扬流波之潢潢兮，体溶溶而东回。',
                '心怊怅以永思兮，意晻晻而日颓。',
                '白露纷以涂涂兮，秋风浏以萧萧。',
                '身永流而不还兮，魂长逝而常愁。',
                '叹曰：',
                '譬彼流水纷扬磕兮，波逢汹涌濆壅滂兮。',
                '揄扬涤荡飘流陨往触崟石兮，龙卬脟圈缭戾宛转阻相薄兮，遭纷逢凶蹇离尤兮，垂文扬采遗将来兮。',
                '离世',
                '灵怀其不吾知兮，灵怀其不吾闻。',
                '就灵怀之皇祖兮，愬灵怀之鬼神。',
                '灵怀曾不吾与兮，即听夫人之谀辞。',
                '余辞上参于天坠兮，旁引之于四时。',
                '指日月使延照兮，抚招摇以质正。',
                '立师旷俾端辞兮，命咎繇使并听。',
                '兆出名曰正则兮，卦发字曰灵均。',
                '余幼既有此鸿节兮，长愈固而弥纯。',
                '不从俗而诐行兮，直躬指而信志。',
                '不枉绳以追曲兮，屈情素以从事。',
                '端余行其如玉兮，述皇舆之踵迹。',
                '群阿容以晦光兮，皇舆覆以幽辟。',
                '舆中涂以回畔兮，驷马惊而横奔。',
                '执组者不能制兮，必折轭而摧辕。',
                '断镳衔以驰骛兮，暮去次而敢止。',
                '路荡荡其无人兮，遂不禦乎千里。',
                '身衡陷而下沉兮，不可获而复登。',
                '不顾身之卑贱兮，惜皇舆之不兴。',
                '出国门而端指兮，冀壹寤而锡还。',
                '哀仆夫之坎毒兮，屡离忧而逢患。',
                '九年之中不吾反兮，思彭咸之水游。',
                '惜师延之浮渚兮，赴汨罗之长流。',
                '遵江曲之逶移兮，触石碕而衡游。',
                '波澧澧而扬浇兮，顺长濑之浊流。',
                '凌黄沱而下低兮，思还流而复反。',
                '玄舆驰而并集兮，身容与而日远。',
                '棹舟杭以横濿兮，济湘流而南极。',
                '立江界而长吟兮，愁哀哀而累息。',
                '情慌忽以忘归兮，神浮游以高历。',
                '心蛩蛩而怀顾兮，魂眷眷而独逝。',
                '叹曰：',
                '余思旧邦心依违兮，日暮黄昏羌幽悲兮，去郢东迁余谁慕兮，谗夫党旅其以兹故兮，河水淫淫情所愿兮，顾瞻郢路终不返兮。',
                '怨思',
                '惟郁郁之忧毒兮，志坎壈而不违。',
                '身憔悴而考旦兮，日黄昏而长悲。',
                '闵空宇之孤子兮，哀枯杨之冤雏。',
                '孤雌吟于高墉兮，鸣鸠栖于桑榆。',
                '玄蝯失于潜林兮，独偏弃而远放。',
                '征夫劳于周行兮，处妇愤而长望。',
                '申诚信而罔违兮，情素洁于纽帛。',
                '光明齐于日月兮，文采耀燿于玉石。',
                '伤压次而不发兮，思沉抑而不扬。',
                '芳懿懿而终败兮，名靡散而不彰。',
                '背玉门以奔骛兮，蹇离尤而干诟。',
                '若龙逢之沉首兮，王子比干之逢醢。',
                '念社稷之几危兮，反为雠而见怨。',
                '思国家之离沮兮，躬获愆而结难。',
                '若青蝇之伪质兮，晋骊姬之反情。',
                '恐登阶之逢殆兮，故退伏于末庭。',
                '孽臣之号咷兮，本朝芜而不治。',
                '犯颜色而触谏兮，反蒙辜而被疑。',
                '菀蘼芜与菌若兮，渐藁本于洿渎。',
                '淹芳芷于腐井兮，弃鸡骇于筐簏。',
                '执棠谿以刜蓬兮，秉干将以割肉。',
                '筐泽泻以豹鞟兮，破荆和以继筑。',
                '时溷浊犹未清兮，世殽乱犹未察。',
                '欲容与以俟时兮，惧年岁之既晏。',
                '顾屈节以从流兮，心巩巩而不夷。',
                '宁浮沅而驰骋兮，下江湘以邅回。',
                '叹曰：',
                '山中槛槛余伤怀兮，征夫皇皇其孰依兮，经营原野杳冥冥兮，乘骐骋骥舒吾情兮，归骸旧邦莫谁语兮，长辞远逝乘湘去兮。',
                '远逝',
                '志隐隐而郁怫兮，愁独哀而冤结。',
                '肠纷纭以缭转兮，涕渐渐其若屑。',
                '情慨慨而长怀兮，信上皇而质正。',
                '合五岳与八灵兮，讯九鬿与六神。',
                '指列宿以白情兮，诉五帝以置辞。',
                '北斗为我折中兮，太一为余听之。',
                '云服阴阳之正道兮，御后土之中和。',
                '佩苍龙之蚴虬兮，带隐虹之逶蛇。',
                '曳彗星之皓旰兮，抚朱爵与鵔鸃。',
                '游清灵之飒戾兮，服云衣之披披。',
                '杖玉策与朱旗兮，垂明月之玄珠。',
                '举霓旌之墆翳兮，建黄纁之总旄。',
                '躬纯粹而罔愆兮，承皇考之妙仪。',
                '惜往事之不合兮，横汨罗而下沥。',
                '乘隆波而南渡兮，逐江湘之顺流。',
                '赴阳侯之潢洋兮，下石濑而登洲。',
                '陆魁堆以蔽视兮，云冥冥而闇前。',
                '山峻高以无垠兮，遂曾闳而迫身。',
                '雪雰雰而薄木兮，云霏霏而陨集。',
                '阜隘狭而幽险兮，石嵾嵯以翳日。',
                '悲故乡而发忿兮，去余邦之弥久。',
                '背龙门而入河兮，登大坟而望夏首。',
                '横舟航而济湘兮，耳聊啾而戃慌。',
                '波淫淫而周流兮，鸿溶溢而滔荡。',
                '路曼曼其无端兮，周容容而无识。',
                '引日月以指极兮，少须臾而释思。',
                '水波远以冥冥兮，眇不睹其东西。',
                '顺风波以南北兮，雾宵晦以纷纷。',
                '日杳杳以西颓兮，路长远而窘迫。',
                '欲酌醴以娱忧兮，蹇骚骚而不释。',
                '叹曰：',
                '飘风蓬龙埃坲々兮，草木摇落时槁悴兮，遭倾遇祸不可救兮，长吟永欷涕究究兮，舒情陈诗冀以自免兮，颓流下陨身日远兮。',
                '惜贤',
                '览屈氏之离骚兮，心哀哀而怫郁。',
                '声嗷嗷以寂寥兮，顾仆夫之憔悴。',
                '拨谄谀而匡邪兮，切淟涊之流俗。',
                '荡渨涹之奸咎兮，夷蠢蠢之溷浊。',
                '怀芬香而挟蕙兮，佩江蓠之婓婓。',
                '握申椒与杜若兮，冠浮云之峨峨。',
                '登长陵而四望兮，览芷圃之蠡蠡。',
                '游兰皋与蕙林兮，睨玉石之嵾嵯。',
                '扬精华以炫燿兮，芳郁渥而纯美。',
                '结桂树之旖旎兮，纫荃蕙与辛夷。',
                '芳若兹而不御兮，捐林薄而菀死。',
                '驱子侨之奔走兮，申徒狄之赴渊。',
                '若由夷之纯美兮，介子推之隐山。',
                '晋申生之离殃兮，荆和氏之泣血。',
                '吴申胥之抉眼兮，王子比干之横废。',
                '欲卑身而下体兮，心隐恻而不置。',
                '方圜殊而不合兮，钩绳用而异态。',
                '欲俟时于须臾兮，日阴曀其将暮。',
                '时迟迟其日进兮，年忽忽而日度。',
                '妄周容而入世兮，内距闭而不开。',
                '俟时风之清激兮，愈氛雾其如塺。',
                '进雄鸠之耿耿兮，谗介介而蔽之。',
                '默顺风以偃仰兮，尚由由而进之。',
                '心懭悢以冤结兮，情舛错以曼忧。',
                '搴薜荔于山野兮，采撚支于中洲。',
                '望高丘而叹涕兮，悲吸吸而长怀。',
                '孰契契而委栋兮，日晻晻而下颓。',
                '叹曰：',
                '江湘油油长流汩兮，挑揄扬汰荡迅疾兮。',
                '忧心展转愁怫郁兮，冤结未舒长隐忿兮，丁时逢殃可奈何兮，劳心悁悁涕滂沱兮。',
                '忧苦',
                '悲余心之悁悁兮，哀故邦之逢殃。',
                '辞九年而不复兮，独茕茕而南行。',
                '思余俗之流风兮，心纷错而不受。',
                '遵野莽以呼风兮，步从容于山廋。',
                '巡陆夷之曲衍兮，幽空虚以寂寞。',
                '倚石岩以流涕兮，忧憔悴而无乐。',
                '登巑岏以长企兮，望南郢而闚之。',
                '山修远其辽辽兮，涂漫漫其无时。',
                '听玄鹤之晨鸣兮，于高冈之峨峨。',
                '独愤积而哀娱兮，翔江洲而安歌。',
                '三鸟飞以自南兮，览其志而欲北。',
                '原寄言于三鸟兮，去飘疾而不可得。',
                '欲迁志而改操兮，心纷结其未离。',
                '外彷徨而游览兮，内恻隐而含哀。',
                '聊须臾以时忘兮，心渐渐其烦错。',
                '原假簧以舒忧兮，志纡郁其难释。',
                '叹《离骚》以扬意兮，犹未殫于《九章》。',
                '长嘘吸以于悒兮，涕横集而成行。',
                '伤明珠之赴泥兮，鱼眼玑之坚藏。',
                '同驽骡与乘駔兮，杂斑駮与阘茸。',
                '葛藟虆于桂树兮，鸱鸮集于木兰。',
                '偓促谈于廊庙兮，律魁放乎山间。',
                '恶虞氏之箫《韶》兮，好遗风之《激楚》。',
                '潜周鼎于江淮兮，爨土鬵于中宇。',
                '且人心之持旧兮，而不可保长。',
                '邅彼南道兮，征夫宵行。',
                '思念郢路兮，还顾睠睠。',
                '涕流交集兮，泣下涟涟。',
                '叹曰：',
                '登山长望中心悲兮，菀彼青青泣如颓兮，留思北顾涕渐渐兮，折锐摧矜凝氾滥兮，念我茕茕魂谁求兮，仆夫慌悴散若流兮。',
                '愍命',
                '昔皇考之嘉志兮，喜登能而亮贤。',
                '情纯洁而罔薉兮，姿盛质而无愆。',
                '放佞人与谄谀兮，斥谗夫与便嬖。',
                '亲忠正之悃诚兮，招贞良与明智。',
                '心溶溶其不可量兮，情澹澹其若渊。',
                '回邪辟而不能入兮，诚原藏而不可迁。',
                '逐下袟于後堂兮，迎虙妃于伊雒。',
                '刜谗贼于中廇兮，选吕管于榛薄。',
                '丛林之下无怨士兮，江河之畔无隐夫。',
                '三苗之徒以放逐兮，伊皋之伦以充庐。',
                '今反表以为里兮，颠裳以为衣。',
                '戚宋万于两楹兮，废周邵于遐夷。',
                '却骐骥以转运兮，腾驴骡以驰逐。',
                '蔡女黜而出帷兮，戎妇入而綵绣服。',
                '庆忌囚于阱室兮，陈不占战而赴围。',
                '破伯牙之号钟兮，挟人筝而弹纬。',
                '藏瑉石于金匮兮，捐赤瑾于中庭。',
                '韩信蒙于介胄兮，行夫将而攻城。',
                '莞芎弃于泽洲兮，瓟瓥蠹于筐簏。',
                '麒麟奔于九皋兮，熊罴群而逸囿。',
                '折芳枝与琼华兮，树枳棘与薪柴。',
                '掘荃蕙与射干兮，耘藜藿与蘘荷。',
                '惜今世其何殊兮，远近思而不同。',
                '或沉沦其无所达兮，或清激其无所通。',
                '哀余生之不当兮，独蒙毒而逢尤。',
                '虽謇謇以申志兮，君乖差而屏之。',
                '诚惜芳之菲菲兮，反以兹为腐也。',
                '怀椒聊之蔎蔎兮，乃逢纷以罹诟也。',
                '叹曰：',
                '嘉皇既殁终不返兮，山中幽险郢路远兮。',
                '谗人諓諓孰可愬兮，征夫罔极谁可语兮。',
                '行吟累欷声喟喟兮，怀忧含戚何侘傺兮。',
                '思古',
                '冥冥深林兮，树木郁郁。',
                '山参差以崭岩兮，阜杳杳以蔽日。',
                '悲余心之悁悁兮，目眇眇而遗泣。',
                '风骚屑以摇木兮，云吸吸以湫戾。',
                '悲余生之无欢兮，愁倥傯于山陆。',
                '旦徘徊于长阪兮，夕彷徨而独宿。',
                '发披披以鬤鬤兮，躬劬劳而瘏悴。',
                '魂俇俇而南行兮，泣霑襟而濡袂。',
                '心婵媛而无告兮，口噤闭而不言。',
                '违郢都之旧闾兮，回湘、沅而远迁。',
                '念余邦之横陷兮，宗鬼神之无次。',
                '闵先嗣之中绝兮，心惶惑而自悲。',
                '聊浮游于山陿兮，步周流于江畔。',
                '临深水而长啸兮，且倘佯而氾观。',
                '兴离骚之微文兮，冀灵修之壹悟。',
                '还余车于南郢兮，复往轨于初古。',
                '道修远其难迁兮，伤余心之不能已。',
                '背三五之典刑兮，绝洪范之辟纪。',
                '播规矩以背度兮，错权衡而任意。',
                '操绳墨而放弃兮，倾容幸而侍侧。',
                '甘棠枯于丰草兮，藜棘树于中庭。',
                '西施斥于北宫兮，仳倠倚于弥楹。',
                '乌获戚而骖乘兮，燕公操于马圉。',
                '蒯聩登于清府兮，咎繇弃而在野。',
                '盖见兹以永叹兮，欲登阶而狐疑。',
                '乘白水而高骛兮，因徙弛而长词。',
                '叹曰：',
                '倘佯垆阪沼水深兮，容与汉渚涕淫淫兮，锺牙已死谁为声兮？纤阿不御焉舒情兮，曾哀悽欷心离离兮，还顾高丘泣如洒兮。',
                '远游',
                '悲余性之不可改兮，屡惩艾而不迻。',
                '服觉皓以殊俗兮，貌揭揭以巍巍。',
                '譬若王侨之乘云兮，载赤霄而凌太清。',
                '欲与天地参寿兮，与日月而比荣。',
                '登昆仑而北首兮，悉灵圉而来谒。',
                '选鬼神于太阴兮，登阊阖于玄阙。',
                '回朕车俾西引兮，褰虹旗于玉门。',
                '驰六龙于三危兮，朝西灵于九滨。',
                '结余轸于西山兮，横飞谷以南征。',
                '绝都广以直指兮，历祝融于硃冥。',
                '枉玉衡于炎火兮，委两馆于咸唐。',
                '贯澒濛以东朅兮，维六龙于扶桑。',
                '周流览于四海兮，志升降以高驰。',
                '徵九神于回极兮，建虹采以招指。',
                '驾鸾凤以上游兮，从玄鹤与鹪明。',
                '孔鸟飞而送迎兮，腾群鹤于瑶光。',
                '排帝宫与罗囿兮，升县圃以眩灭。',
                '结琼枝以杂佩兮，立长庚以继日。',
                '凌惊雷以轶骇电兮，缀鬼谷于北辰。',
                '鞭风伯使先驱兮，囚灵玄于虞渊。',
                '遡高风以低佪兮，览周流于朔方。',
                '就颛顼而敶辞兮，考玄冥于空桑。',
                '旋车逝于崇山兮，奏虞舜于苍梧。',
                '济杨舟于会稽兮，就申胥于五湖。',
                '见南郢之流风兮，殒余躬于沅湘。',
                '望旧邦之黯黮兮，时溷浊其犹未央。',
                '怀兰茝之芬芳兮，妒被离而折之。',
                '张绛帷以襜襜兮，风邑邑而蔽之。',
                '日暾暾其西舍兮，阳焱焱而复顾。',
                '聊假日以须臾兮，何骚骚而自故。',
                '叹曰：',
                '譬彼蛟龙乘云浮兮，汎淫澒溶纷若雾兮。',
                '潺湲轇轕雷动电发馺高举兮。',
                '升虚凌冥沛浊浮清入帝宫兮，摇翘奋羽驰风骋雨游无穷兮。',
            ],
            'spell' => [
                'féng fēn',
                'yī bó yōng zhī mò zhòu xī, liàng huáng zhí zhī qū yuán.',
                'yún yú zhào zǔ yú gāo yáng xī, wéi chǔ huái zhī chán lián.',
                'yuán shēng shòu mìng yú zhēn jié xī, hóng yǒng lù yǒu jiā míng.',
                'qí míng zì yú tiān dì xī, bìng guāng míng yú liè xīng.',
                'xī jīng cuì ér tǔ fēn zhuó xī, héng xié shì ér bù qǔ róng.',
                'xíng kòu chéng ér bù ā xī, suì jiàn pái ér féng chán.',
                'hòu tīng xū ér chù shí xī, bù wú lǐ ér shùn qíng.',
                'cháng fèn yuān ér hán nù xī, zhì qiān jiǎn ér zuǒ qīng.',
                'xīn tǎng huāng qí bù wǒ yǔ xī, gōng sù sù qí bù wú qīn.',
                'cí líng xiū ér yǔn zhì xī, yín zé pàn zhī jiāng bīn.',
                'jiāo guì luó yǐ diān fù xī, yǒu jié xìn ér guī chéng.',
                'chán fū ǎi ǎi ér màn zhe xī, hé qí bù shū yǔ qíng?',
                'shǐ jié yán yú miào táng xī, xìn zhōng tú ér pàn zhī.',
                'huái lán huì yǔ héng zhǐ xī, xíng zhōng yě ér sàn zhī.',
                'shēng āi āi ér huái gāo qiū xī, xīn chóu chóu ér sī jiù bāng.',
                'yuàn chéng xián ér zì shì xī, jìng yín yì ér dào yōng.',
                'yán méi lí yǐ jǔ bài xī, jīng yuè liè ér shuāi mào.',
                'shang chān chān ér hán fēng xī, yī nà nà ér yǎn lù.',
                'fù jiāng xiāng zhī tuān liú xī, shùn bō còu ér xià jiàng.',
                'xú pái huái yú shān ā xī, piāo fēng lái zhī xiōng xiōng.',
                'chí yú chē xī xuán shí, bù yú mǎ xī dòng tíng.',
                'píng míng fā xī cāng wú, xī tóu sù xī shí chéng.',
                'fú róng gài ér líng huá chē xī, zǐ bèi quē ér yù táng.',
                'bì lì shì ér lù lí jiàn xī, yú lín yī ér bái ní shang.',
                'dēng féng lóng ér xià yǔn xī, wéi gù dū zhī màn màn.',
                'sī nán yǐng zhī jiù sú xī, cháng yī xī ér jiǔ yùn.',
                'yáng liú bō zhī huáng huáng xī, tǐ róng róng ér dōng huí.',
                'xīn chāo chàng yǐ yǒng sī xī, yì àn àn ér rì tuí.',
                'bái lù fēn yǐ tú tú xī, qiū fēng liú yǐ xiāo xiāo.',
                'shēn yǒng liú ér bù hái xī, hún cháng shì ér cháng chóu.',
                'tàn yuē:',
                'pì bǐ liú shuǐ fēn yáng kē xī, bō féng xiōng yǒng fén yōng pāng xī.',
                'yú yáng dí dàng piāo liú yǔn wǎng chù yín shí xī,',
                'lóng áng liè quān liáo lì wǎn zhuǎn zǔ xiāng báo xī,',
                'zāo fēn féng xiōng jiǎn lí yóu xī, chuí wén yáng cǎi yí jiāng lái xī.',
                'lí shì',
                'líng huái qí bù wú zhī xī, líng huái qí bù wú wén.',
                'jiù líng huái zhī huáng zǔ xī, sù líng huái zhī guǐ shén.',
                'líng huái céng bù wú yǔ xī, jí tīng fū rén zhī yú cí.',
                'yú cí shàng cān yú tiān zhuì xī, páng yǐn zhī yú sì shí.',
                'zhǐ rì yuè shǐ yán zhào xī, fǔ zhāo yáo yǐ zhì zhèng.',
                'lì shī kuàng bǐ duān cí xī, mìng jiù yáo shǐ bìng tīng.',
                'zhào chū míng yuē zhèng zé xī, guà fā zì yuē líng jūn.',
                'yú yòu jì yǒu cǐ hóng jié xī, zhǎng yù gù ér mí chún.',
                'bù cóng sú ér bì xíng xī, zhí gōng zhǐ ér xìn zhì.',
                'bù wǎng shéng yǐ zhuī qū xī, qū qíng sù yǐ cóng shì.',
                'duān yú xíng qí rú yù xī, shù huáng yú zhī zhǒng jī.',
                'qún ā róng yǐ huì guāng xī, huáng yú fù yǐ yōu pì.',
                'yú zhōng tú yǐ huí pàn xī, sì mǎ jīng ér héng bēn.',
                'zhí zǔ zhě bù néng zhì xī, bì zhé è ér cuī yuán.',
                'duàn biāo xián yǐ chí wù xī, mù qù cì ér gǎn zhǐ.',
                'lù dàng dàng qí wú rén xī, suì bù yù hū qiān lǐ.',
                'shēn héng xiàn ér xià chén xī, bù kě huò ér fù dēng.',
                'bù gù shēn zhī bēi jiàn xī, xī huáng yú zhī bù xīng.',
                'chū guó mén ér duān zhǐ xī, jì yī wù ér xī hái.',
                'āi pū fū zhī kǎn dú xī, lǚ lí yōu ér féng huàn.',
                'jiǔ nián zhī zhōng bù wú fǎn xī, sī péng xián zhī shuǐ yóu.',
                'xī shī yán zhī fú zhǔ xī, fù mì luó zhī cháng liú.',
                'zūn jiāng qū zhī wēi yí xī, chù shí qí ér héng yóu.',
                'bō lǐ lǐ ér yáng jiāo xī, shùn zhǎng lài zhī zhuó liú.',
                'líng huáng tuó ér xià dī xī, sī hái liú ér fù fǎn.',
                'xuán yú chí ér bìng jí xī, shēn róng yǔ ér rì yuǎn.',
                'zhào zhōu háng yǐ héng lì xī, jì xiāng liú ér nán jí.',
                'lì jiāng jiè ér cháng yín xī, chóu āi āi ér lèi xī.',
                'qíng huāng hū yǐ wàng guī xī, shén fú yóu yǐ gāo lì.',
                'xīn qióng qióng ér huái gù xī, hún juàn juàn ér dú shì.',
                'tàn yuē:',
                'yú sī jiù bāng xīn yī wéi xī,',
                'rì mù huáng hūn qiāng yōu bēi xī,',
                'qù yǐng dōng qiān yú shuí mù xī,',
                'chán fū dǎng lǚ qí yǐ zī gù xī,',
                'hé shuǐ yín yín qíng suǒ yuàn xī,',
                'gù zhān yǐng lù zhōng bù fǎn xī.',
                'yuàn sī',
                'wéi yù yù zhī yōu dú xī, zhì kǎn lǎn ér bù wéi.',
                'shēn qiáo cuì ér kǎo dàn xī, rì huáng hūn ér zhǎng bēi.',
                'mǐn kōng yǔ zhī gū zǐ xī, āi kū yáng zhī yuān chú.',
                'gū cí yín yú gāo yōng xī, míng jiū qī yú sāng yú.',
                'xuán yuán shī yú qián lín xī, dú piān qì ér yuǎn fàng.',
                'zhēng fū láo yú zhōu xíng xī, chù fù fèn ér zhǎng wàng.',
                'shēn chéng xìn ér wǎng wéi xī, qíng sù jié yú niǔ bó.',
                'guāng míng qí yú rì yuè xī, wén cǎi yào yào yú yù shí.',
                'shāng yā cì ér bù fā xī, sī chén yì ér bù yáng.',
                'fāng yì yì ér zhōng bài xī, míng mí sàn ér bù zhāng.',
                'bèi yù mén yǐ bēn wù xī, jiǎn lí yóu ér gàn gòu.',
                'ruò lóng féng zhī chén shǒu xī, wáng zǐ bǐ gàn zhī féng hǎi.',
                'niàn shè jì zhī jǐ wēi xī, fǎn wèi chóu ér jiàn yuàn.',
                'sī guó jiā zhī lí jǔ xī, gōng huò qiān ér jié nán.',
                'ruò qīng yíng zhī wěi zhì xī, jìn lí jī zhī fǎn qíng.',
                'kǒng dēng jiē zhī féng dài xī, gù tuì fú yú mò tíng.',
                'niè chén zhī hào táo xī, běn cháo wú ér bù zhì.',
                'fàn yán sè ér chù jiàn xī, fǎn méng gū ér bèi yí.',
                'wǎn mí wú yǔ jūn ruò xī, jiàn gǎo běn yú wū dú.',
                'yān fāng zhǐ yú fǔ jǐng xī, qì jī hài yú kuāng lù.',
                'zhí táng xī yǐ fú péng xī, bǐng gàn jiàng yǐ gē ròu.',
                'kuāng zé xiè yǐ bào kuò xī, pò jīng hé yǐ jì zhù.',
                'shí hùn zhuó yóu wèi qīng xī, shì xiáo luàn yóu wèi chá.',
                'yù róng yǔ yǐ qí shí xī, jù nián suì zhī jì yàn.',
                'gù qū jié yǐ cóng liú xī, xīn gǒng gǒng ér bù yí.',
                'níng fú yuán ér chí chěng xī, xià jiāng xiāng yǐ zhān huí.',
                'tàn yuē:',
                'shān zhōng kǎn kǎn yú shāng huái xī, zhēng fū huáng huáng qí shú yī xī,',
                'jīng yíng yuán yě yǎo míng míng xī, chéng qí chěng jì shū wú qíng xī,',
                'guī hái jiù bāng mò shuí yǔ xī, cháng cí yuǎn shì chéng xiāng qù xī.',
                'yuǎn shì',
                'zhì yǐn yǐn ér yù fú xī, chóu dú āi ér yuān jié.',
                'cháng fēn yún yǐ liáo zhuǎn xī, tì jiàn jiàn qí ruò xiè.',
                'qíng kǎi kǎi ér zhǎng huái xī, xìn shàng huáng ér zhì zhèng.',
                'hé wǔ yuè yǔ bā líng xī, xùn jiǔ qí yǔ liù shén.',
                'zhǐ liè sù yǐ bái qíng xī, sù wǔ dì yǐ zhì cí.',
                'běi dǒu wèi wǒ zhé zhōng xī, tài yī wèi yú tīng zhī.',
                'yún fú yīn yáng zhī zhèng dào xī, yù hòu tǔ zhī zhōng hé.',
                'pèi cāng lóng zhī yòu qiú xī, dài yǐn hóng zhī wēi shé.',
                'yè huì xīng zhī hào gàn xī, fǔ zhū jué yǔ jùn yí.',
                'yóu qīng líng zhī sà lì xī, fú yún yī zhī pī pī.',
                'zhàng yù cè yǔ zhū qí xī, chuí míng yuè zhī xuán zhū.',
                'jǔ ní jīng zhī zhì yì xī, jiàn huáng xūn zhī zǒng máo.',
                'gōng chún cuì ér wǎng qiān xī, chéng huáng kǎo zhī miào yí.',
                'xī wǎng shì zhī bù hé xī, héng mì luó ér xià lì.',
                'chéng lóng bō ér nán dù xī, zhú jiāng xiāng zhī shùn liú.',
                'fù yáng hóu zhī huáng yáng xī, xià shí lài ér dēng zhōu.',
                'lù kuí duī yǐ bì shì xī, yún míng míng ér àn qián.',
                'shān jùn gāo yǐ wú yín xī, suì céng hóng ér pò shēn.',
                'xuě fēn fēn ér báo mù xī, yún fēi fēi ér yǔn jí.',
                'fù ài xiá ér yōu xiǎn xī, shí cēn cuó yǐ yì rì.',
                'bēi gù xiāng ér fā fèn xī, qù yú bāng zhī mí jiǔ.',
                'bèi lóng mén ér rù hé xī, dēng dà fén ér wàng xià shǒu.',
                'héng zhōu háng ér jì xiāng xī, ěr liáo jiū ér tǎng huāng.',
                'bō yín yín ér zhōu liú xī, hóng róng yì ér tāo dàng.',
                'lù màn màn qí wú duān xī, zhōu róng róng ér wú shí.',
                'yǐn rì yuè yǐ zhǐ jí xī, shǎo xū yú ér shì sī.',
                'shuǐ bō yuǎn yǐ míng míng xī, miǎo bù dǔ qí dōng xī.',
                'shùn fēng bō yǐ nán běi xī, wù xiāo huì yǐ fēn fēn.',
                'rì yǎo yǎo yǐ xī tuí xī, lù cháng yuǎn ér jiǒng pò.',
                'yù zhuó lǐ yǐ yú yōu xī, jiǎn sāo sāo ér bù shì.',
                'tàn yuē:',
                'piāo fēng péng lóng āi fó xī, cǎo mù yáo luò shí gǎo cuì xī,',
                'zāo qīng yù huò bù kě jiù xī, cháng yín yǒng xī tì jiū jiū xī,',
                'shū qíng chén shī jì yǐ zì miǎn xī, tuí liú xià yǔn shēn rì yuǎn xī.',
                'xī xián',
                'lǎn qū shì zhī lí sāo xī, xīn āi āi ér fú yù.',
                'shēng áo áo yǐ jì liáo xī, gù pū fū zhī qiáo cuì.',
                'bō chǎn yú ér kuāng xié xī, qiè tiǎn niǎn zhī liú sú.',
                'dàng wēi wō zhī jiān jiù xī, yí chǔn chǔn zhī hùn zhuó.',
                'huái fēn xiāng ér xié huì xī, pèi jiāng lí zhī fēi fēi.',
                'wò shēn jiāo yǔ dù ruò xī, guān fú yún zhī é é.',
                'dēng cháng líng ér sì wàng xī, lǎn zhǐ pǔ zhī lí lí.',
                'yóu lán gāo yǔ huì lín xī, nì yù shí zhī cēn cuó.',
                'yáng jīng huá yǐ xuàn yào xī, fāng yù wò ér chún měi.',
                'jié guì shù zhī yǐ nǐ xī, rèn quán huì yǔ xīn yí.',
                'fāng ruò zī ér bù yù xī, juān lín báo ér wǎn sǐ.',
                'qū zi qiáo zhī bēn zǒu xī, shēn tú dí zhī fù yuān.',
                'ruò yóu yí zhī chún měi xī, jiè zǐ tuī zhī yǐn shān.',
                'jìn shēn shēng zhī lí yāng xī, jīng hé shì zhī qì xuè.',
                'wú shēn xū zhī jué yǎn xī, wáng zǐ bǐ gàn zhī héng fèi.',
                'yù bēi shēn ér xià tǐ xī, xīn yǐn cè ér bù zhì.',
                'fāng huán shū ér bù hé xī, gōu shéng yòng ér yì tài.',
                'yù qí shí yú xū yú xī, rì yīn yì qí jiāng mù.',
                'shí chí chí qí rì jìn xī, nián hū hū ér rì dù.',
                'wàng zhōu róng ér rù shì xī, nèi jù bì ér bù kāi.',
                'qí shí fēng zhī qīng jī xī, yù fēn wù qí rú méi.',
                'jìn xióng jiū zhī gěng gěng xī, chán jiè jiè ér bì zhī.',
                'mò shùn fēng yǐ yǎn yǎng xī, shàng yóu yóu ér jìn zhī.',
                'xīn kuǎng liàng yǐ yuān jié xī, qíng chuǎn cuò yǐ màn yōu.',
                'qiān bì lì yú shān yě xī, cǎi niǎn zhī yú zhōng zhōu.',
                'wàng gāo qiū ér tàn tì xī, bēi xī xī ér zhǎng huái.',
                'shú qì qì ér wěi dòng xī, rì àn àn ér xià tuí.',
                'tàn yuē:',
                'jiāng xiāng yóu yóu cháng liú gǔ xī, tiāo yú yáng tài dàng xùn jí xī.',
                'yōu xīn zhǎn zhuǎn chóu fú yù xī, yuān jié wèi shū zhǎng yǐn fèn xī,',
                'dīng shí féng yāng kě nài hé xī, láo xīn yuān yuān tì pāng tuó xī.',
                'yōu kǔ',
                'bēi yú xīn zhī yuān yuān xī, āi gù bāng zhī féng yāng.',
                'cí jiǔ nián ér bù fù xī, dú qióng qióng ér nán xíng.',
                'sī yú sú zhī liú fēng xī, xīn fēn cuò ér bù shòu.',
                'zūn yě mǎng yǐ hū fēng xī, bù cóng róng yú shān sōu.',
                'xún lù yí zhī qū yǎn xī, yōu kōng xū yǐ jì mò.',
                'yǐ shí yán yǐ liú tì xī, yōu qiáo cuì ér wú lè.',
                'dēng cuán wán yǐ zhǎng qǐ xī, wàng nán yǐng ér kuī zhī.',
                'shān xiū yuǎn qí liáo liáo xī, tú màn màn qí wú shí.',
                'tīng xuán hè zhī chén míng xī, yú gāo gāng zhī é é.',
                'dú fèn jī ér āi yú xī, xiáng jiāng zhōu ér ān gē.',
                'sān niǎo fēi yǐ zì nán xī, lǎn qí zhì ér yù běi.',
                'yuán jì yán yú sān niǎo xī, qù piāo jí ér bù kě dé.',
                'yù qiān zhì ér gǎi cāo xī, xīn fēn jié qí wèi lí.',
                'wài páng huáng ér yóu lǎn xī, nèi cè yǐn ér hán āi.',
                'liáo xū yú yǐ shí wàng xī, xīn jiàn jiàn qí fán cuò.',
                'yuán jiǎ huáng yǐ shū yōu xī, zhì yū yù qí nán shì.',
                'tàn lí sāo yǐ yáng yì xī, yóu wèi dān yú jiǔ zhāng.',
                'zhǎng xū xī yǐ yú yì xī, tì héng jí ér chéng háng.',
                'shāng míng zhū zhī fù ní xī, yú yǎn jī zhī jiān cáng.',
                'tóng nú luó yǔ chéng zǎng xī, zá bān bó yǔ tà róng.',
                'gé lěi léi yú guì shù xī, chī xiāo jí yú mù lán.',
                'wò cù tán yú láng miào xī, lǜ kuí fàng hū shān jiān.',
                'è yú shì zhī xiāo sháo xī, hǎo yí fēng zhī jī chǔ.',
                'qián zhōu dǐng yú jiāng huái xī, cuàn tǔ qín yú zhōng yǔ.',
                'qiě rén xīn zhī chí jiù xī, ér bù kě bǎo cháng.',
                'zhān bǐ nán dào xī, zhēng fū xiāo xíng.',
                'sī niàn yǐng lù xī, hái gù juàn juàn.',
                'tì liú jiāo jí xī, qì xià lián lián.',
                'tàn yuē:',
                'dēng shān cháng wàng zhōng xīn bēi xī, wǎn bǐ qīng qīng qì rú tuí xī,',
                'liú sī běi gù tì jiàn jiàn xī, zhé ruì cuī jīn níng fàn làn xī,',
                'niàn wǒ qióng qióng hún shuí qiú xī, pū fū huāng cuì sàn ruò liú xī.',
                'mǐn mìng',
                'xī huáng kǎo zhī jiā zhì xī, xǐ dēng néng ér liàng xián.',
                'qíng chún jié ér wǎng huì xī, zī shèng zhì ér wú qiān.',
                'fàng nìng rén yǔ chǎn yú xī, chì chán fū yǔ biàn bì.',
                'qīn zhōng zhèng zhī kǔn chéng xī, zhāo zhēn liáng yǔ míng zhì.',
                'xīn róng róng qí bù kě liàng xī, qíng dàn dàn qí ruò yuān.',
                'huí xié pì ér bù néng rù xī, chéng yuán cáng ér bù kě qiān.',
                'zhú xià zhì yú hòu táng xī, yíng fú fēi yú yī luò.',
                'fú chán zéi yú zhōng liù xī, xuǎn lǚ guǎn yú zhēn báo.',
                'cóng lín zhī xià wú yuàn shì xī, jiāng hé zhī pàn wú yǐn fū.',
                'sān miáo zhī tú yǐ fàng zhú xī, yī gāo zhī lún yǐ chōng lú.',
                'jīn fǎn biǎo yǐ wéi lǐ xī, diān shang yǐ wéi yī.',
                'qī sòng wàn yú liǎng yíng xī, fèi zhōu shào yú xiá yí.',
                'què qí jì yǐ zhuǎn yùn xī, téng lǘ luó yǐ chí zhú.',
                'cài nǚ chù ér chū wéi xī, róng fù rù ér cǎi xiù fú.',
                'qìng jì qiú yú jǐng shì xī, chén bù zhàn zhàn ér fù wéi.',
                'pò bó yá zhī hào zhōng xī, xié rén zhēng ér dàn wěi.',
                'cáng mín shí yú jīn kuì xī, juān chì jǐn yú zhōng tíng.',
                'hán xìn méng yú jiè zhòu xī, xíng fū jiāng ér gōng chéng.',
                'guǎn qiōng qì yú zé zhōu xī, bó lì dù yú kuāng lù.',
                'qí lín bēn yú jiǔ gāo xī, xióng pí qún ér yì yòu.',
                'zhé fāng zhī yǔ qióng huá xī, shù zhǐ jí yǔ xīn chái.',
                'jué quán huì yǔ yè gān xī, yún lí huò yǔ ráng hé.',
                'xī jīn shì qí hé shū xī, yuǎn jìn sī ér bù tóng.',
                'huò chén lún qí wú suǒ dá xī, huò qīng jī qí wú suǒ tōng.',
                'āi yú shēng zhī bù dàng xī, dú méng dú ér féng yóu.',
                'suī jiǎn jiǎn yǐ shēn zhì xī, jūn guāi chà ér píng zhī.',
                'chéng xī fāng zhī fēi fēi xī, fǎn yǐ zī wèi fǔ yě.',
                'huái jiāo liáo zhī shè shè xī, nǎi féng fēn yǐ lí gòu yě.',
                'tàn yuē:',
                'jiā huáng jì mò zhōng bù fǎn xī, shān zhōng yōu xiǎn yǐng lù yuǎn xī.',
                'chán rén jiàn jiàn shú kě sù xī, zhēng fū wǎng jí shuí kě yǔ xī.',
                'xíng yín lèi xī shēng kuì kuì xī, huái yōu hán qī hé chà chì xī.',
                'sī gǔ',
                'míng míng shēn lín xī, shù mù yù yù.',
                'shān cēn cī yǐ zhǎn yán xī, fù yǎo yǎo yǐ bì rì.',
                'bēi yú xīn zhī yuān yuān xī, mù miǎo miǎo ér yí qì.',
                'fēng sāo xiè yǐ yáo mù xī, yún xī xī yǐ jiǎo lì.',
                'bēi yú shēng zhī wú huān xī, chóu kōng zǒng yú shān lù.',
                'dàn pái huái yú zhǎng bǎn xī, xī páng huáng ér dú sù.',
                'fā pī pī yǐ ráng ráng xī, gōng qú láo ér tú cuì.',
                'hún guàng guàng ér nán xíng xī, qì zhān jīn ér rú mèi.',
                'xīn chán yuán ér wú gào xī, kǒu jìn bì ér bù yán.',
                'wéi yǐng dū zhī jiù lǘ xī, huí xiāng yuán ér yuǎn qiān.',
                'niàn yú bāng zhī héng xiàn xī, zōng guǐ shén zhī wú cì.',
                'mǐn xiān sì zhī zhōng jué xī, xīn huáng huò ér zì bēi.',
                'liáo fú yóu yú shān xiá xī, bù zhōu liú yú jiāng pàn.',
                'lín shēn shuǐ ér cháng xiào xī, qiě cháng yáng ér fàn guān.',
                'xìng lí sāo zhī wēi wén xī, jì líng xiū zhī yī wù.',
                'hái yú chē yú nán yǐng xī, fù wǎng guǐ yú chū gǔ.',
                'dào xiū yuǎn qí nán qiān xī, shāng yú xīn zhī bù néng yǐ.',
                'bèi sān wǔ zhī diǎn xíng xī, jué hóng fàn zhī pì jì.',
                'bō guī jǔ yǐ bèi dù xī, cuò quán héng ér rèn yì.',
                'cāo shéng mò ér fàng qì xī, qīng róng xìng ér shì cè.',
                'gān táng kū yú fēng cǎo xī, lí jí shù yú zhōng tíng.',
                'xī shī chì yú běi gōng xī, pǐ suī yǐ yú mí yíng.',
                'wū huò qī ér cān chéng xī, yàn gōng cāo yú mǎ yǔ.',
                'kuǎi kuì dēng yú qīng fǔ xī, jiù yáo qì ér zài yě.',
                'gài jiàn zī yǐ yǒng tàn xī, yù dēng jiē ér hú yí.',
                'chéng bái shuǐ ér gāo wù xī, yīn xǐ chí ér zhǎng cí.',
                'tàn yuē:',
                'cháng yáng lú bǎn zhǎo shuǐ shēn xī, róng yǔ hàn zhǔ tì yín yín xī,',
                'zhōng yá yǐ sǐ shuí wèi shēng xī? xiān ā bù yù yān shū qíng xī,',
                'céng āi qī xī xīn lí lí xī, hái gù gāo qiū qì rú sǎ xī.',
                'yuǎn yóu',
                'bēi yú xìng zhī bù kě gǎi xī, lǚ chéng ài ér bù yí.',
                'fú jué hào yǐ shū sú xī, mào jiē jiē yǐ wēi wēi.',
                'pì ruò wáng qiáo zhī chéng yún xī, zài chì xiāo ér líng tài qīng.',
                'yù yǔ tiān dì cān shòu xī, yǔ rì yuè ér bǐ róng.',
                'dēng kūn lún ér běi shǒu xī, xī líng yǔ ér lái yè.',
                'xuǎn guǐ shén yú tài yīn xī, dēng chāng hé yú xuán quē.',
                'huí zhèn chē bǐ xī yǐn xī, qiān hóng qí yú yù mén.',
                'chí liù lóng yú sān wēi xī, cháo xī líng yú jiǔ bīn.',
                'jié yú zhěn yú xī shān xī, héng fēi gǔ yǐ nán zhēng.',
                'jué dōu guǎng yǐ zhí zhǐ xī, lì zhù róng yú zhū míng.',
                'wǎng yù héng yú yán huǒ xī, wěi liǎng guǎn yú xián táng.',
                'guàn hòng méng yǐ dōng qiè xī, wéi liù lóng yú fú sāng.',
                'zhōu liú lǎn yú sì hǎi xī, zhì shēng jiàng yǐ gāo chí.',
                'zhēng jiǔ shén yú huí jí xī, jiàn hóng cǎi yǐ zhāo zhǐ.',
                'jià luán fèng yǐ shàng yóu xī, cóng xuán hè yǔ jiāo míng.',
                'kǒng niǎo fēi ér sòng yíng xī, téng qún hè yú yáo guāng.',
                'pái dì gōng yǔ luó yòu xī, shēng xiàn pǔ yǐ xuàn miè.',
                'jié qióng zhī yǐ zá pèi xī, lì cháng gēng yǐ jì rì.',
                'líng jīng léi yǐ yì hài diàn xī, zhuì guǐ gǔ yú běi chén.',
                'biān fēng bó shǐ xiān qū xī, qiú líng xuán yú yú yuān.',
                'sù gāo fēng yǐ dī huí xī, lǎn zhōu liú yú shuò fāng.',
                'jiù zhuān xū ér zhèn cí xī, kǎo xuán míng yú kōng sāng.',
                'xuán chē shì yú chóng shān xī, zòu yú shùn yú cāng wú.',
                'jì yáng zhōu yú kuài jī xī, jiù shēn xū yú wǔ hú.',
                'jiàn nán yǐng zhī liú fēng xī, yǔn yú gōng yú yuán xiāng.',
                'wàng jiù bāng zhī àn dǎn xī, shí hùn zhuó qí yóu wèi yāng.',
                'huái lán chǎi zhī fēn fāng xī, dù bèi lí ér zhé zhī.',
                'zhāng jiàng wéi yǐ chān chān xī, fēng yì yì ér bì zhī.',
                'rì tūn tūn qí xī shě xī, yáng yàn yàn ér fù gù.',
                'liáo jià rì yǐ xū yú xī, hé sāo sāo ér zì gù.',
                'tàn yuē:',
                'pì bǐ jiāo lóng chéng yún fú xī,',
                'fàn yín hòng róng fēn ruò wù xī.',
                'chán yuán jiāo gé léi dòng diàn fà sà gāo jǔ xī.',
                'shēng xū líng míng pèi zhuó fú qīng rù dì gōng xī,',
                'yáo qiào fèn yǔ chí fēng chěng yǔ yóu wú qióng xī.',
            ],
            'vernacular' => [
                '<strong>逢纷</strong>',
                '我是伯庸的后代啊，是正直诚信的屈原。',
                '我的始祖是古帝高阳氏啊，楚怀王与我同根相连。',
                '我秉受正气而生啊，生辰合道起了美名。',
                '我的名字与天地相齐啊，光辉灿烂如同群星。',
                '我吸天地精华吐出浊气啊，身处浊世也决不苟合求容。',
                '我行为忠诚刚直不阿啊，于是遭谗害被弃置不用。',
                '君王听信假话贬斥忠良啊，不理睬我反顺从邪恶奸佞。',
                '我心怀愤恨满腔怒火啊，我心遭压抑失去平衡。',
                '心神恍惚啊君王不与我同心，孤独冷落啊君王不同我亲近。',
                '我辞别君王心灰意冷啊，低吟悲歌在泽畔水滨。',
                '先贤遭祸身危难啊，依然竭尽忠信一片诚心。',
                '众谗人嘁嘁喳喳抑人扬己啊，君王何不昭示我的真情！',
                '当初我们曾在庙堂约好啊，如今却听信谗言中途变心。',
                '我怀揣兰蕙和衡芷啊，却被抛弃荒野不用。',
                '怀念故土高山声声哀叹啊，思恋祖国家乡满怀愁情。',
                '我本想找机会自能竭尽忠心啊，怎奈道路堵塞幽暗不通。',
                '面目黧黑人憔悴啊，身老力衰没精神。',
                '阵阵冷风吹动我的裙裳啊，浓浓寒露打湿我的衣裙。',
                '奔赴湍急的长江和湘水啊，顺随波涛向下漂行。',
                '我慢步徘徊在山窝啊，山风阵阵回旋凶猛。',
                '驾起我的车啊向玄石山奔驰，让我的马儿啊在洞庭山慢步徐行。',
                '黎明我从苍梧山出发啊，傍晚我投宿在石城山顶。',
                '荷花车盖菱花车啊，紫贝楼台白玉厅。',
                '薜荔为装饰美玉做卧席啊，五彩的上衣，洁白的裙裳。',
                '登上逢龙山向下眺望啊，离开故都道路多么漫长。',
                '想起那郢都的风物习俗啊，一夜之间九转愁肠。',
                '波高流急茫茫一片啊，浪涛翻滚奔向东方。',
                '心惆怅止不住的思念啊，精神郁闷一天天倍觉神伤。',
                '霜露一片白茫茫啊，秋风急吹萧萧响。',
                '身随水流不回返啊，灵魂远逝愁难当。',
                '尾声：',
                '就像那奔腾的江水，轰轰隆响啊。',
                '风卷大波浪翻滚，浩浩荡荡啊。',
                '大风鼓荡，波浪起伏，撞击巨石啊。',
                '打着旋涡，盘旋冲击，水流终究被阻挡啊。',
                '时逢浊世遭凶险，终获罪愆啊。',
                '留下清词丽句美篇，传于来世后人观。',
        ),
              
        array (
                '<strong>离世</strong>',
                '怀王不知道我的清白啊，怀王不了解我的忠诚。',
                '我要向怀王的先祖倾诉心曲啊，我要向怀王的神灵诉说冤情。',
                '怀王本不与我志同道合啊，又听信那小人的阿谀奉承。',
                '我说的话上合天地啊，四时之神也可以作证。',
                '让日月长照监察啊，让北斗来质对证明。',
                '我的话可请师旷来考察啊，可令法官皋陶一起来听。',
                '通过卜兆我起名叫正则啊，根据卦象我的表字叫灵均。',
                '我小时候已有大节美行啊，长大后更加坚定而纯正。',
                '从不随波逐流胡作妄行啊，我身心正直，意志坚定。',
                '决不违反正道追求邪曲啊，委屈自己的意志苟合求容。',
                '我的行为端正纯洁如玉啊，继承先王治国的正道传统。',
                '众小人花言巧语蒙蔽君王啊，致使国家处于危险黑暗之中。',
                '就像车行中途突然回转啊，马儿受惊狂奔驰骋。',
                '车夫不能控制啊，必然轭断辕毁车倾。',
                '勒口断折惊马飞驰啊，直到傍晚无人敢停。',
                '宽阔的大道空无一人啊，脱缰的野马千里奔行。',
                '我横遭陷害被贬落啊，不能再获得君王的信用。',
                '我不顾念自身的卑贱啊，我哀伤的是祖国不能强盛。',
                '我走出城门可依然忠心耿耿啊，希望君王一旦醒悟召我回朝廷。',
                '仆夫为我愤愤不平啊，可怜我屡受迫害和不幸。',
                '放逐九年不召还我啊，真想与彭咸一起游水戏浪。',
                '可羡师延投水免遭刑罚啊，我也要举身自沉汨罗江。',
                '沿着曲折的江水宛转漂流啊，船触石岸掉头就横走。',
                '波声隆隆回波浪卷啊，顺水驶向浅滩的浊流。',
                '乘着夏水顺流而下啊，多想遇回水使我转回头。',
                '船儿飞驰并肩齐进啊，我随波逐浪一天天远去。',
                '摇起船桨把大江横渡啊，渡过湘水奔向南方极远之处。',
                '我站在江岸高歌长吟啊，心中愁苦止不住声声叹息。',
                '神情恍惚忘了归去啊，精神高高飞行在天际。',
                '心怀忧愁思恋故乡啊，灵魂依依不舍孤独远去。',
                '尾声：',
                '我思念故国啊，心中犹豫迟疑。',
                '暮色苍苍啊，心中一片忧苦。',
                '离开郢都东去啊，我是思恋谁？',
                '小人太多啊，使我落到这地步。',
                '河水滔滔东流啊，真愿像它那样无虑无忧。',
                '回望郢都的道路啊，我再也不能踏上归途。',
        ),
              
        array (
                '<strong>怨思</strong>',
                '心情郁闷忧愁怨恨啊，命运虽坎坷也决不背弃理想。',
                '我憔悴痛苦一夜到天明啊，从清晨到傍晚难排悲伤。',
                '可怜独居空室的孤儿啊，哀伤小鸟栖息在老树枯杨。',
                '失伴的雌鸟在高墙上悲啼啊，鸠鸟在桑树上声声鸣唱。',
                '黑猿离开了茂密的山林啊，孤零零被丢弃在远方。',
                '征夫在大道上奔波不息啊，家中妻子含恨相思盼望。',
                '我坚守诚信之道决不背离啊，我的感情就如束帛纯洁无伤。',
                '我的美德与日月齐辉啊，我的文采与美玉争光。',
                '可伤身遭压迫不能振发啊，情思受到压抑不得高扬。',
                '香气郁郁终于消散啊，身败名灭不显不彰。',
                '离开君王奔向远方啊，忠贞获罪自取祸殃。',
                '就好像关龙逄被杀掉了头啊，也似王子比干遇害被开膛。',
                '我担心祖国危在旦夕啊，反与小人结仇遭恨怨。',
                '我思虑国家纲纪遭破坏啊，自己反倒获罪招患难。',
                '小人就像青蝇变白为黑啊，晋国骊姬挑拨亲情进谗言。',
                '我怕亲近君王遭遇灾祸啊，所以我退身隐伏荒野泽畔。',
                '佞臣贼子吵吵嚷嚷啊，朝无贤良一片混乱。',
                '我不惜触犯君王忠言直谏啊，反倒蒙受罪过被君王猜疑。',
                '蘼芜杜若被堆积不用啊，藁本被浸在小水沟里。',
                '芬芳的白芷泡在臭水井啊，鸡骇犀被丢进草筐竹器。',
                '用棠谿利剑去割蓬蒿野草啊，用干将宝剑当厨刀砍肉剖皮。',
                '豹皮口袋装满泽泻恶草啊，用大杵捣碎美玉和氏璧。',
                '时世浑浊美丑不清啊，世道混乱好坏不明。',
                '我想慢慢地等待时机啊，又担心年纪已老等不及。',
                '想要委屈心志随流从俗啊，可总是七上八下心有忧惧。',
                '宁愿浮身沅水漂流而去啊，进长江入湘水天涯浪迹。',
                '尾声：',
                '车行山中声声响，我心中悲伤啊。',
                '征夫惴惴心不安，他的归宿在何方啊。',
                '荒原山野苦奔波，杳无人迹草木莽莽啊。',
                '乘上骏马奔驰啊，寻求贤君舒泄我的情肠。',
                '死后尸骨也要埋故乡，此心此情向谁讲啊。',
                '永别了，我要远去，乘舟湘水漂流远方。',
        ),
              
        array (
                '<strong>远逝</strong>',
                '心中忧伤郁闷不快啊，满腹冤屈独自哀伤。',
                '愁肠百转心乱如麻啊，止不住的泪水滚滚流淌。',
                '心中愤懑慨然长叹思念不止啊，我要向上帝申诉为我作证明。',
                '五岳八方的神灵齐来考察啊，可向九鬿六宗众神灵讯问。',
                '我指着众星列宿发誓啊，我向五方天帝倾诉我的衷情。',
                '北斗可证明我中正不偏啊，太一帝为我辨别善恶奸忠。',
                '遵循天地阴阳之正道啊，坚持大地的中和之行。',
                '驾御青龙蜿蜒飞行啊，系着长长的绚丽彩虹。',
                '彗星紧紧跟随一道光明啊，乘坐着朱雀鵕鸡向上飞行。',
                '我遨游在清凉的高空啊，我身披长长的五彩云衣。',
                '手持玉花和红色大旗啊，身佩光耀闪闪的明月珠。',
                '高举起云旗遮天蔽日啊，竖起五色旄缨的金黄旗。',
                '我品行纯正没有瑕疵啊，我继承了先父的美好风仪。',
                '可叹从前与君不能配合啊，只好南下横渡汨罗江。',
                '乘着滚滚波涛向南行进啊，顺着长江湘水追波逐浪。',
                '奔向那浩渺的大水浪涛啊，越过急流险滩登上山岛。',
                '高耸的大山挡住我的视线啊，浓云一片眼前一片晦暗。',
                '群山高峻连绵不断啊，山势峥嵘直逼面前。',
                '大雪纷纷覆盖山林啊，乌云密布低沉翻卷。',
                '山高谷狭幽深险峻啊，怪石嶙嶙遮住阳光。',
                '可怜远离故乡心里怨恨啊，我离开故国日子已经很长。',
                '走出郢都东门进入大河啊，我登上高岸把夏口眺望。',
                '掉转船头把湘水渡过啊，我一阵阵耳鸣精神恍惚忧伤。',
                '波涛连天打着旋涡翻滚啊，大水浩茫奔流一片汪洋。',
                '道路漫长遥远没有尽头啊，周围一片纷乱没有标志。',
                '依靠着日月北极来指引啊，才一下消除心头的忧思。',
                '江水深远望不到头啊，一片浩渺不辨东西。',
                '顺风随波漂南荡北啊，大雾弥漫如夜似漆。',
                '太阳遥遥向西落下啊，路途迢迢忧心难舒。',
                '我本想一醉解千愁啊，可愁思绵绵难消除。',
                '尾声：',
                '旋风盘旋尘土飞扬啊，草木随风凋落枝枯叶飞。',
                '遭难遇祸不可挽救啊，悲吟长叹止不住的泪水。',
                '赋诗抒怀希望免祸啊，随水日益远去故国难回。',
        ),
              
        array (
                '<strong>惜贤</strong>',
                '读完屈原的《离骚》啊，我心郁闷悲伤不畅快。',
                '我大声疾呼而无人应啊，看那仆人也都憔悴伤怀。',
                '我要整治奸佞匡正邪恶啊，要涤荡卑浊的世风流俗。',
                '我要扫荡污秽以除谗佞啊，要铲除无礼的贪残之徒。',
                '我怀抱美好手持蕙草啊，我身佩江离芳香浓郁。',
                '我手持申椒和杜若啊，头戴切云冠高耸巍峨。',
                '登上高山四面眺望啊，看到园圃中香芷行行。',
                '在长满兰草的水边和蕙林游玩啊，一回眸又见一片玉石林千姿百态。',
                '美玉鲜花闪耀着明亮的光辉啊，散发出醉人的浓香纯真美好。',
                '我系结上柔嫩的桂树枝啊，再联缀上荃草香蕙和辛夷。',
                '如此芳香的花草不被佩戴啊，反把它抛弃在丛林堆积枯死。',
                '我要跟随王子乔奔走前后啊。',
                '又想学申徒狄投渊洁身自好。',
                '又想像许由伯夷清高纯洁啊，像介子推隐身深山无所贪求。',
                '可怜晋国申生被谗遭祸啊，可叹楚国卞和抱玉泣血。',
                '吴国子胥死后挖去两眼啊，王子比干横遭剖心之祸。',
                '我欲卑躬屈膝顺从世俗啊，可心中作痛不忍放弃美德。',
                '方与圆形状不同不能相合啊，钩绳用处不同因而曲直有别。',
                '我欲稍等片刻美好时光啊，可是日色昏昏残阳将西落。',
                '时光一天天地慢慢流逝啊，年岁却匆匆地一天天度过。',
                '我想苟合求容以迎合时俗啊，可是心里总是拒绝不愿行。',
                '我欲等待时政清明风气变啊，可雾气愈来愈浓如尘蔽空。',
                '想像雄鸠那样进献微末诚信啊，谗谄小人又百般阻挠蒙蔽圣听。',
                '想默默地随风俯仰顺从流俗啊，心中又犹豫不甘堕落丧失操行。',
                '心里不快愁肠百结啊，心绪繁乱忧思深长。',
                '我在山野摘取芳草薜荔啊，采集香草撚支在小洲上。',
                '我北望高山叹息流涕啊，止不住的悲泣长思难忘。',
                '怎不怀忧令人志消神伤啊，太阳渐渐昏暗沉落西方。',
                '尾声：',
                '江湘滔滔不断东流啊，鼓浪扬波飞流而去。',
                '辗转反侧忧愁难眠啊，怨情难消长恨难驱。',
                '生不逢时有何办法啊，心中忧愁泪落如雨。',
        ),
              
        array (
                '<strong>忧苦</strong>',
                '我心里一片忧苦悲伤啊，痛惜祖国又遭受祸殃。',
                '离开郢都九年不能归啊，我孑然一身走向南方。',
                '想起楚国的污浊世风啊，我心绪烦乱不能忍受。',
                '沿着山野我呼唤清平啊，山弯弯里我慢步行走。',
                '我在平坦的山窝里巡行啊，四周一片空虚寂寞无声。',
                '我身靠着山岩悲痛流涕啊，我心中忧苦憔悴无欢情。',
                '登上高高山顶久立长望啊，看一看故乡望一望南郢。',
                '山峦绵绵一眼望不到头啊，路途遥遥归期无奈难定。',
                '耳听神鸟玄鹤引颈晨鸣啊，看见它站立在峨峨山顶。',
                '孤独愤闷我要排解哀思啊，游江中芳洲纵情歌唱。',
                '三青鸟从南方翩翩飞来啊，看它神态想要飞向北方。',
                '我想让三青鸟为我捎信啊，它疾速飞去我难寄衷肠。',
                '我想改变志向和节操啊，可心乱如麻忠诚难忘。',
                '表面上我自由自在地游览啊，可内心忧痛含悲满怀哀伤。',
                '暂且求得片刻时光把忧思忘却啊，可忧愁烦乱又渐渐堵满心房。',
                '我希望鼓瑟吹笙舒解忧愤啊，可心中愁思百结难遣难忘。',
                '悲吟《离骚》抒怀明志啊，心中忧苦难尽诉于《九章》。',
                '我止不住的抽泣声声悲啼啊，拭不干的涕泪满面交流成行。',
                '把明珠丢进泥里令人伤心啊，把鱼眼当做宝珠严严收藏。',
                '把骡子和骏马混同一样啊，无才无德之徒杂集一堂。',
                '恶草葛藟爬满桂树枝干啊，恶鸟鸱鸮落在木兰树上。',
                '贪愚小人在朝堂高谈阔论啊，高士贤良却放逐山野蛮荒。',
                '厌弃古乐虞舜的箫《韶》啊，却把流行的《激楚》欣赏。',
                '传国九鼎沉入江淮啊，反把土锅摆在殿堂。',
                '人心怀有淳朴的古风啊，但世风日下难保久长。',
                '我转身登上向南的道路啊，就像征夫昼夜辛苦奔忙。',
                '我思念着回郢的道路啊，一步三回首难舍难忘。',
                '禁不住的涕泣交流啊，老泪纵横滚滚流淌。',
                '尾声：',
                '登上高山远望，心中无限悲伤啊。',
                '看那草木茂盛，眼泪流水般流淌啊。',
                '思念故乡回头北望，禁不住泪水浪浪啊。',
                '摧折我的意志信念，与世俗随声应响啊。',
                '可自念我孤单一人，我找谁侍奉君王啊？',
                '我的仆人慌恐愁苦，像流水般的散亡啊。',
        ),
              
        array (
                '<strong>愍命</strong>',
                '当年我先父志向美好啊，喜欢推举俊才和贤能。',
                '他情性纯洁身无污秽啊，行为无过失姿质美盛。',
                '远逐奸佞和谄谀小人啊，斥退谗夫和嬖爱近臣。',
                '亲近诚厚的忠正之士啊，招纳贤良和明智之人。',
                '他心胸开阔不可度量啊，性情恬逸深渊般沉静。',
                '邪僻的言行难以侵入啊，永葆忠诚之志不变更。',
                '把乱政的侍妾从后宫中赶出啊，把贤女宓妃从洛水迎进宫中。',
                '把谗夫佞贼从朝廷逐出啊，把吕望管仲从民间选进朝中。',
                '让山野之中没有怨恨之士啊，使江边泽畔没有隐居的贤能。',
                '把三苗之类的奸佞通通放逐啊，让伊尹皋陶样的贤臣充满朝廷。',
                '如今善恶不分里外颠倒啊，反把裙裳当成上衣。',
                '亲近宋万之流置于高位啊，反把周公邵公放逐废弃。',
                '弃千里马不用让它拉车负重啊，却乘驾驴骡让它飞奔驰骋。',
                '把蔡国美女贬逐赶出帷帐啊，反纳戎狄丑妇让她着彩披凤。',
                '勇士庆忌囚禁在地牢啊，却让懦夫陈不占解围出征。',
                '摔碎伯牙名琴号钟啊，反把小筝弹奏拨弄。',
                '把石头珍藏在金匮里啊，却把美玉抛弃在院中。',
                '韩信身披铠甲只当小卒啊，反让小兵为大将率兵攻城。',
                '把芳草莞芎遗弃在水泽啊，匏瓢藏在竹器让虫蛀尽。',
                '麒麟奔窜在水泊大泽啊，熊罴成群在御苑安然徘徊。',
                '把芳枝玉花摧残折尽啊，却栽植多刺的枳棘和木柴。',
                '挖掉香草荃蕙和射干啊，却把藜藿蘘荷恶草败叶栽。',
                '可惜今世与从前多么悬殊啊，想想先前看看现今真不相同。',
                '有人沉沦世俗不能显达啊，有人清明自励不为世容。',
                '可怜我生不逢时啊，独受苦难遭罪过。',
                '我虽忠直地表明心志啊，但与君心相违遭排斥。',
                '我真诚爱惜芬芳香气啊，君王反说这是腐臭气息。',
                '怀揣椒聊香气四溢啊，竟逢乱世身遭打击。',
                '尾声：',
                '圣君已经逝世，一去不回返啊。',
                '山中幽暗危险，郢都路遥远啊。',
                '谗人花言巧语，可向谁诉说啊，行人前途茫茫，又能向谁言啊。',
                '边走边吟边长叹，一声声悲叹不断啊。',
                '忧愁凄苦满心怀，穷愁潦倒悲无限啊。',
        ),
              
        array (
                '<strong>思古</strong>',
                '山林一片阴暗幽深啊，树木繁茂葱葱郁郁。',
                '高山起伏峥嵘险峻啊，峻岭绵绵遮天蔽日。',
                '可怜我心中无限愁苦啊，我两眼模糊泪下如雨。',
                '疾风萧萧摇动草木啊，浓云团团翻滚飘浮。',
                '可怜我一生毫无欢乐啊，忧愁困苦在野岭荒山。',
                '白天我在长长山坡游荡啊，夜晚我辗转反侧独宿孤眠。',
                '我披头散发一头散乱啊，我劳苦憔悴病病恹恹。',
                '我神魂不定匆匆南行啊，我泪水不止沾湿衣衫。',
                '心中忧愁凄苦向谁诉说啊，我只好噤声闭口不语不言。',
                '离开郢都我的故里家乡啊，渡过湘江沅水漂泊远迁。',
                '念我的祖国横遭危难啊，宗庙无人祭祀香火断。',
                '哀怜祖宗事业无人继承啊，心中惶惶恐惧自伤自怜。',
                '暂且在山峡行走游荡啊，信步周游在大江岸畔。',
                '面临江水放声长啸啊，徘徊徜徉纵日游观。',
                '作《离骚》隐约谏戒君王啊，盼君王顿然醒悟更张改弦。',
                '召还我的车驾回郢都啊，重修先王的旧规常典。',
                '道路遥远实难回还啊，可伤我一片思君之心不断。',
                '君王背离三皇五帝的常法啊，断绝《洪范》的纲纪法宪。',
                '抛弃圆规矩尺而违背法度啊，丢开衡称而任意称重量短。',
                '执持法纪的人被弃置不用啊，阿谀谗谄小人陪侍在君前。',
                '甘棠枯死在野草丛中啊，蒺藜荆棘却种满庭院。',
                '美女西施被贬出宫中啊，丑妇仳倠反侍立堂前。',
                '乌获得宠与君王同车共乘啊，燕公养马操劳在马厩圈栏。',
                '蒯瞆忤逆不义反进宗庙啊，皋陶贤明却弃逐荒野山间。',
                '见是非如此颠倒使我长叹啊，想进身献忠心又迟疑难决断。',
                '还是乘浮白水远走高飞吧，趁此退身永别这龌龊世间。',
                '尾声：',
                '徜徉在垆山坡池水深深啊，徘徊在汉水边涕泪涟涟。',
                '子期伯牙已死谁把琴音弹奏啊，纤阿不把车驾，怎能把技艺献？',
                '倍增哀伤凄然长叹，心肠痛断啊，回望高山悲痛泣下，泪洒江天。',
        ),
              
        array (
                '<strong>远游</strong>',
                '可悲我忠直的本性不可改变啊，虽然屡遭打击也坚守不移。',
                '我披服众芳艳丽鲜明与众不同啊，我志愿高远巍然充塞天地。',
                '愿像仙人王乔乘云驾雾啊，驾起红云飞行遨游在太空。',
                '愿与天地同寿长命无期啊，与日月同辉齐放光明。',
                '登上昆仑山北向天门啊，众仙人齐来拜见接迎。',
                '在北极挑选忠正的鬼神啊，与我从玄阙山同登天庭。',
                '掉转我的车驾向西行啊，高举虹旗直驱玉门山顶。',
                '驾起六龙奔驰在三危仙山啊，召西方众神灵齐会九曲水滨。',
                '让我的车驾绕过西山啊，横度飞泉谷向南奔行。',
                '穿越都广山野一直向南啊，经过海神祝融的驻地朱冥。',
                '回转车驾绕过大火山啊，我在咸池两次驻马暂停。',
                '穿过鸿蒙之气向东去啊，到东海扶桑树上拴六龙。',
                '我遍行天下周游四海啊，我上天下地奔走飞行。',
                '召九天神灵聚会天中啊，高树彩旗指挥四方神灵。',
                '乘驾鸾风向上飞行啊，紧紧跟随玄鹤和鹪明。',
                '孔鸟飞舞来往迎送啊，群鹤飞集在北极之星。',
                '排开帝宫和天苑啊，登上悬圃目炫销魂。',
                '系结玉枝增加佩饰啊，太阳隐没再升起长庚。',
                '乘惊雷追逐奔逸的闪电啊，把害人的百鬼锁在北极星。',
                '驱赶风伯让他前面开路啊，再把玄帝暂囚禁在虞渊中。',
                '迎着高风在高空徘徊啊，我要把北方周游遍行。',
                '我向颛顼帝陈述衷情啊，再到空桑山考问玄冥。',
                '转过车头再驰向崇山啊，再至苍梧山向舜帝奏明。',
                '驾起杨木轻舟来至会稽啊，向伍子胥问道在五湖之中。',
                '看见楚国窳败的政治和恶俗啊，我自沉沅湘坚守峻洁的操行。',
                '望故乡一片昏暗不明啊，世道混乱污浊方兴未尽。',
                '怀抱兰草白茝一派芳香啊，反遭奸人嫉妒被摧残凋零。',
                '君王张设绛帷多么鲜明美好啊，然政风衰颓正好自蔽圣聪。',
                '明亮亮的太阳西山隐没啊，余光闪耀还想高照当空。',
                '暂且趁此时光游戏片刻啊，可愁思如故难得欢情。',
                '尾声：',
                '就像那水中蛟龙，腾云驾雾飞升啊，在浓云里浮游，纷然如雾一片蒙蒙啊。',
                '蜿蜒纵横如水流，雷鸣电闪，飞向高空啊。',
                '飞上天空，弃去污浊乘清风，进入帝宫啊。',
                '摆龙尾振双翅，乘风驾雨，遨游太空啊。',
            ],
            'notes' => [
            ],
            'unscramble' => [
            ],
        ],
    ],
];
