<?php
return [
        'id' => 3702,
        'title' => '追格小程序你期望发布什么功能模块？',
        //'title' => '你关注什么样的商城模块',
        'excerpt' => '你关注什么样的商城模块，欢迎投票。',
        //'excerpt' => '你期望追格发布什么功能模块？欢迎跟帖回复！',
        'type' => 'multi',
        //'type' => 'pk',
        'count' => 159,
        'option_a' => [
          'opt' => 'a',
          'image' => 'https://q.zhuige.com/wp-content/uploads/2022/11/jq1669539665RMGJDM.jpg',
          'title' => '情怀',
          'count' => 156,
          'rate' => 61,
          'xuan' => 0,
        ],
        'option_b' => [
          'opt' => 'b',
          'image' => 'https://q.zhuige.com/wp-content/uploads/2022/11/jq1669539668JEMHBA.jpg',
          'title' => '盈利',
          'count' => 99,
          'rate' => 39,
          'xuan' => 0,
        ],

        'options' => [
          [
            'opt' => '1',
            'title' => '微信流量主（圈子模块）',
            'count' => 73,
            'rate' => 24,
            'xuan' => 0,
          ],
          [
            'opt' => '2',
            'title' => '敏感词库',
            'count' => 43,
            'rate' => 14,
            'xuan' => 0,
          ],
          [
            'opt' => '3',
            'title' => '商城（基于WP）',
            'count' => 60,
            'rate' => 20,
            'xuan' => 0,
          ],
          [
            'opt' => '4',
            'title' => '闲置物品',
            'count' => 48,
            'rate' => 16,
            'xuan' => 0,
          ],
          [
            'opt' => '5',
            'title' => '系统消息',
            'count' => 38,
            'rate' => 13,
            'xuan' => 0,
          ],
          5 => 
          [
            'opt' => '6',
            'title' => '其他请跟帖回复',
            'count' => 26,
            'rate' => 9,
            'xuan' => 0,
          ],
        ],
        'deadline' => '05/16/2023',
        'my_vote' => '',
        'is_end' => 1,
        'post_type' => 'zhuige_vote',
        'post_type_name' => '投票',
        'link' => '/pages/vote/detail/detail',
        'author' => [],
        'time' => '2022-11-28',
        'stick' => 0,
];
