<?php
return [
    'lisao' => ['code' => 'lisao', 'name' => '离骚', 'nameFull' => '离骚', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'tianwen' => ['code' => 'tianwen', 'name' => '天问', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'yuanyou' => ['code' => 'yuanyou', 'name' => '远游', 'nameFull' => '远游', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'buju' => ['code' => 'buju', 'name' => '卜居', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'yufu' => ['code' => 'yufu', 'name' => '渔父', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'zhaohun' => ['code' => 'zhaohun', 'name' => '招魂', 'nameFull' => '招魂', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'dazhao' => ['code' => 'dazhao', 'name' => '大招', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_donghuangtaiyi' => ['code' => 'jg_donghuangtaiyi', 'name' => '东皇太一', 'nameFull' => '九歌-东皇太一', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_yunzhongjun' => ['code' => 'jg_yunzhongjun', 'name' => '云中君', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_xiangjun' => ['code' => 'jg_xiangjun', 'name' => '湘君', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_xiangfuren' => ['code' => 'jg_xiangfuren', 'name' => '湘夫人', 'nameFull' => '湘夫人', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_dasiming' => ['code' => 'jg_dasiming', 'name' => '大司命', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_shaosiming' => ['code' => 'jg_shaosiming', 'name' => '少司命', 'nameFull' => '少司命', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_dongjun' => ['code' => 'jg_dongjun', 'name' => '东君', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_hebo' => ['code' => 'jg_hebo', 'name' => '河伯', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_shangui' => ['code' => 'jg_shangui', 'name' => '山鬼', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_guoshang' => ['code' => 'jg_guoshang', 'name' => '国殇', 'nameFull' => '九歌-国殇', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jg_lihun' => ['code' => 'jg_lihun', 'name' => '礼魂', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_xisong' => ['code' => 'jz_xisong', 'name' => '惜诵', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_shejiang' => ['code' => 'jz_shejiang', 'name' => '涉江', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_aiying' => ['code' => 'jz_aiying', 'name' => '哀郢', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_chousi' => ['code' => 'jz_chousi', 'name' => '抽思', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_huaisha' => ['code' => 'jz_huaisha', 'name' => '怀沙', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_simeiren' => ['code' => 'jz_simeiren', 'name' => '思美人', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_xiwangri' => ['code' => 'jz_xiwangri', 'name' => '惜往日', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_jusong' => ['code' => 'jz_jusong', 'name' => '橘颂', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jz_beihuifeng' => ['code' => 'jz_beihuifeng', 'name' => '悲回风', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jiubian' => ['code' => 'jiubian', 'name' => '九辩 (宋玉)', 'nameFull' => '九辩-宋玉', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'xishi' => ['code' => 'xishi', 'name' => '惜誓 (贾谊)', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'zhaoyinshi' => ['code' => 'zhaoyinshi', 'name' => '招隐士 (淮南小山)', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'qijian' => ['code' => 'qijian', 'name' => '七谏(东方朔)', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'aishiming' => ['code' => 'aishiming', 'name' => '哀时命(庄忌)', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jiuhuai' => ['code' => 'jiuhuai', 'name' => '九怀(王褒)', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jiutan' => ['code' => 'jiutan', 'name' => '九叹(刘向)', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
    'jiusi' => ['code' => 'jiusi', 'name' => '九思(王逸)', 'nameFull' => '', 'spell' => '', 'brief' => '', 'keyword' => ''],
];
