<?php
return [
    '1' => ['code' => '1', 'name' => '亲士', 'nameFull' => '墨子01章 亲士', 'brief' => '', 'keyword' => '墨子,亲士'],
    '2' => ['code' => '2', 'name' => '修身', 'nameFull' => '墨子02章 修身', 'brief' => '', 'keyword' => '墨子,修身'],
    '3' => ['code' => '3', 'name' => '所染', 'nameFull' => '墨子03章 所染', 'brief' => '', 'keyword' => '墨子,所染'],
    '4' => ['code' => '4', 'name' => '法仪', 'nameFull' => '墨子04章 法仪', 'brief' => '', 'keyword' => '墨子,法仪'],
    '5' => ['code' => '5', 'name' => '七患', 'nameFull' => '墨子05章 七患', 'brief' => '', 'keyword' => '墨子,七患'],
    '6' => ['code' => '6', 'name' => '辞过', 'nameFull' => '墨子06章 辞过', 'brief' => '', 'keyword' => '墨子,辞过'],
    '7' => ['code' => '7', 'name' => '三辩', 'nameFull' => '墨子07章 三辩', 'brief' => '', 'keyword' => '墨子,三辩'],
    '8' => ['code' => '8', 'name' => '尚贤(上)', 'nameFull' => '墨子08章 尚贤(上)', 'brief' => '', 'keyword' => '墨子,尚贤(上)'],
    '9' => ['code' => '9', 'name' => '尚贤(中)', 'nameFull' => '墨子09章 尚贤(中)', 'brief' => '', 'keyword' => '墨子,尚贤(中)'],
    '10' => ['code' => '10', 'name' => '尚贤(下)', 'nameFull' => '墨子10章 尚贤(下)', 'brief' => '', 'keyword' => '墨子,尚贤(下)'],
    '11' => ['code' => '11', 'name' => '尚同(上)', 'nameFull' => '墨子11章 尚同(上)', 'brief' => '', 'keyword' => '墨子,尚同(上)'],
    '12' => ['code' => '12', 'name' => '尚同(中)', 'nameFull' => '墨子12章 尚同(中)', 'brief' => '', 'keyword' => '墨子,尚同(中)'],
    '13' => ['code' => '13', 'name' => '尚同(下)', 'nameFull' => '墨子13章 尚同(下)', 'brief' => '', 'keyword' => '墨子,尚同(下)'],
    '14' => ['code' => '14', 'name' => '兼爱(上)', 'nameFull' => '墨子14章 兼爱(上)', 'brief' => '', 'keyword' => '墨子,兼爱(上)'],
    '15' => ['code' => '15', 'name' => '兼爱(中)', 'nameFull' => '墨子15章 兼爱(中)', 'brief' => '', 'keyword' => '墨子,兼爱(中)'],
    '16' => ['code' => '16', 'name' => '兼爱(下)', 'nameFull' => '墨子16章 兼爱(下)', 'brief' => '', 'keyword' => '墨子,兼爱(下)'],
    '17' => ['code' => '17', 'name' => '非攻(上)', 'nameFull' => '墨子17章 非攻(上)', 'brief' => '', 'keyword' => '墨子,非攻(上)'],
    '18' => ['code' => '18', 'name' => '非攻(中)', 'nameFull' => '墨子18章 非攻(中)', 'brief' => '', 'keyword' => '墨子,非攻(中)'],
    '19' => ['code' => '19', 'name' => '非攻(下)', 'nameFull' => '墨子19章 非攻(下)', 'brief' => '', 'keyword' => '墨子,非攻(下)'],
    '20' => ['code' => '20', 'name' => '节用(上)', 'nameFull' => '墨子20章 节用(上)', 'brief' => '', 'keyword' => '墨子,节用(上)'],
    '21' => ['code' => '21', 'name' => '节用(中)', 'nameFull' => '墨子21章 节用(中)', 'brief' => '', 'keyword' => '墨子,节用(中)'],
    '22' => ['code' => '22', 'name' => '节用(下)', 'nameFull' => '墨子22章 节用(下)', 'brief' => '', 'keyword' => '墨子,节用(下)'],
    '23' => ['code' => '23', 'name' => '节葬(上)(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '24' => ['code' => '24', 'name' => '节葬(中)(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '25' => ['code' => '25', 'name' => '节葬(下)', 'nameFull' => '墨子25章 节葬(下)', 'brief' => '', 'keyword' => '墨子,节葬(下)'],
    '26' => ['code' => '26', 'name' => '天志(上)', 'nameFull' => '墨子26章 天志(上)', 'brief' => '', 'keyword' => '墨子,天志(上)'],
    '27' => ['code' => '27', 'name' => '天志(中)', 'nameFull' => '墨子27章 天志(中)', 'brief' => '', 'keyword' => '墨子,天志(中)'],
    '28' => ['code' => '28', 'name' => '天志(下)', 'nameFull' => '墨子28章 天志(下)', 'brief' => '', 'keyword' => '墨子,天志(下)'],
    '29' => ['code' => '29', 'name' => '明鬼(上)(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '30' => ['code' => '30', 'name' => '明鬼(中)(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '31' => ['code' => '31', 'name' => '明鬼(下)', 'nameFull' => '墨子31章 明鬼(下)', 'brief' => '', 'keyword' => '墨子,明鬼(下)'],
    '32' => ['code' => '32', 'name' => '非乐(上)', 'nameFull' => '墨子32章 非乐(上)', 'brief' => '', 'keyword' => '墨子,非乐(上)'],
    '33' => ['code' => '33', 'name' => '非乐(中)(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '34' => ['code' => '34', 'name' => '非乐(下)(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '35' => ['code' => '35', 'name' => '非命(上)', 'nameFull' => '墨子35章 非命(上)', 'brief' => '', 'keyword' => '墨子,非命(上)'],
    '36' => ['code' => '36', 'name' => '非命(中)', 'nameFull' => '墨子36章 非命(中)', 'brief' => '', 'keyword' => '墨子,非命(中)'],
    '37' => ['code' => '37', 'name' => '非命(下)', 'nameFull' => '墨子37章 非命(下)', 'brief' => '', 'keyword' => '墨子,非命(下)'],
    '38' => ['code' => '38', 'name' => '非儒(上)(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '39' => ['code' => '39', 'name' => '非儒(下)', 'nameFull' => '墨子39章 非儒(下)', 'brief' => '', 'keyword' => '墨子,非儒(下)'],
    '40' => ['code' => '40', 'name' => '经(上)', 'nameFull' => '墨子40章 经(上)', 'brief' => '', 'keyword' => '墨子,经(上)'],
    '41' => ['code' => '41', 'name' => '经(下)', 'nameFull' => '墨子41章 经(下)', 'brief' => '', 'keyword' => '墨子,经(下)'],
    '42' => ['code' => '42', 'name' => '经说(上)', 'nameFull' => '墨子42章 经说(上)', 'brief' => '', 'keyword' => '墨子,经说(上)'],
    '43' => ['code' => '43', 'name' => '经说(下)', 'nameFull' => '墨子43章 经说(下)', 'brief' => '', 'keyword' => '墨子,经说(下)'],
    '44' => ['code' => '44', 'name' => '大取', 'nameFull' => '墨子44章 大取', 'brief' => '', 'keyword' => '墨子,大取'],
    '45' => ['code' => '45', 'name' => '小取', 'nameFull' => '墨子45章 小取', 'brief' => '', 'keyword' => '墨子,小取'],
    '46' => ['code' => '46', 'name' => '耕柱', 'nameFull' => '墨子46章 耕柱', 'brief' => '', 'keyword' => '墨子,耕柱'],
    '47' => ['code' => '47', 'name' => '贵义', 'nameFull' => '墨子47章 贵义', 'brief' => '', 'keyword' => '墨子,贵义'],
    '48' => ['code' => '48', 'name' => '公孟', 'nameFull' => '墨子48章 公孟', 'brief' => '', 'keyword' => '墨子,公孟'],
    '49' => ['code' => '49', 'name' => '鲁问', 'nameFull' => '墨子49章 鲁问', 'brief' => '', 'keyword' => '墨子,鲁问'],
    '50' => ['code' => '50', 'name' => '公输', 'nameFull' => '墨子50章 公输', 'brief' => '', 'keyword' => '墨子,公输'],
    '51' => ['code' => '51', 'name' => '囗囗(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '52' => ['code' => '52', 'name' => '备城门', 'nameFull' => '墨子52章 备城门', 'brief' => '', 'keyword' => '墨子,备城门', 'isLost' => 1],
    '53' => ['code' => '53', 'name' => '备高临', 'nameFull' => '墨子53章 备高临', 'brief' => '', 'keyword' => '墨子,备高临'],
    '54' => ['code' => '54', 'name' => '囗囗囗(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '55' => ['code' => '55', 'name' => '囗囗囗(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '56' => ['code' => '56', 'name' => '备梯', 'nameFull' => '墨子56章 备梯', 'brief' => '', 'keyword' => '墨子,备梯'],
    '57' => ['code' => '57', 'name' => '囗囗(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '58' => ['code' => '58', 'name' => '备水', 'nameFull' => '墨子58章 备水', 'brief' => '', 'keyword' => '墨子,备水'],
    '59' => ['code' => '59', 'name' => '囗囗(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '60' => ['code' => '60', 'name' => '囗囗(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '61' => ['code' => '61', 'name' => '备突', 'nameFull' => '墨子61章 备突', 'brief' => '', 'keyword' => '墨子,备突'],
    '62' => ['code' => '62', 'name' => '备穴', 'nameFull' => '墨子62章 备穴', 'brief' => '', 'keyword' => '墨子,备穴'],
    '63' => ['code' => '63', 'name' => '备蛾傅', 'nameFull' => '墨子63章 备蛾傅', 'brief' => '', 'keyword' => '墨子,备蛾傅'],
    '64' => ['code' => '64', 'name' => '(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '65' => ['code' => '65', 'name' => '(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '66' => ['code' => '66', 'name' => '(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '67' => ['code' => '67', 'name' => '(亡)', 'nameFull' => '', 'brief' => '', 'keyword' => '', 'isLost' => 1],
    '68' => ['code' => '68', 'name' => '迎敌祠', 'nameFull' => '墨子68章 迎敌祠', 'brief' => '', 'keyword' => '墨子,迎敌祠'],
    '69' => ['code' => '69', 'name' => '旗帜', 'nameFull' => '墨子69章 旗帜', 'brief' => '', 'keyword' => '墨子,旗帜'],
    '70' => ['code' => '70', 'name' => '号令', 'nameFull' => '墨子70章 号令', 'brief' => '', 'keyword' => '墨子,号令'],
    '71' => ['code' => '71', 'name' => '杂守', 'nameFull' => '墨子71章 杂守', 'brief' => '', 'keyword' => '墨子,杂守'],
];
