<?php
return [
    '1' => ['code' => '1', 'name' => '劝学', 'nameFull' => '劝学篇第一', 'brief' => '', 'keyword' => '荀子,劝学'],
    '2' => ['code' => '2', 'name' => '修身', 'nameFull' => '修身篇第二', 'brief' => '', 'keyword' => '荀子,修身'],
    '3' => ['code' => '3', 'name' => '不苟', 'nameFull' => '不苟篇第三', 'brief' => '', 'keyword' => '荀子,不苟'],
    '4' => ['code' => '4', 'name' => '荣辱', 'nameFull' => '荣辱篇第四', 'brief' => '', 'keyword' => '荀子,荣辱'],
    '5' => ['code' => '5', 'name' => '非相', 'nameFull' => '非相篇第五', 'brief' => '', 'keyword' => '荀子,非相'],
    '6' => ['code' => '6', 'name' => '非十二子', 'nameFull' => '非十二子篇第六', 'brief' => '', 'keyword' => '荀子,非十二子'],
    '7' => ['code' => '7', 'name' => '仲尼', 'nameFull' => '仲尼篇第七', 'brief' => '', 'keyword' => '荀子,仲尼'],
    '8' => ['code' => '8', 'name' => '儒效', 'nameFull' => '儒效篇第八', 'brief' => '', 'keyword' => '荀子,儒效'],
    '9' => ['code' => '9', 'name' => '王制', 'nameFull' => '王制篇第九', 'brief' => '', 'keyword' => '荀子,王制'],
    '10' => ['code' => '10', 'name' => '富国', 'nameFull' => '富国篇第十', 'brief' => '', 'keyword' => '荀子,富国'],
    '11' => ['code' => '11', 'name' => '王霸', 'nameFull' => '王霸篇第十一', 'brief' => '', 'keyword' => '荀子,王霸'],
    '12' => ['code' => '12', 'name' => '君道', 'nameFull' => '君道篇第十二', 'brief' => '', 'keyword' => '荀子,君道'],
    '13' => ['code' => '13', 'name' => '臣道', 'nameFull' => '臣道篇第十三', 'brief' => '', 'keyword' => '荀子,臣道'],
    '14' => ['code' => '14', 'name' => '致士', 'nameFull' => '致士篇第十四', 'brief' => '', 'keyword' => '荀子,致士'],
    '15' => ['code' => '15', 'name' => '议兵', 'nameFull' => '议兵篇第十五', 'brief' => '', 'keyword' => '荀子,议兵'],
    '16' => ['code' => '16', 'name' => '强国', 'nameFull' => '强国篇第十六', 'brief' => '', 'keyword' => '荀子,强国'],
    '17' => ['code' => '17', 'name' => '天论', 'nameFull' => '天论篇第十七', 'brief' => '', 'keyword' => '荀子,天论'],
    '18' => ['code' => '18', 'name' => '正论', 'nameFull' => '正论篇第十八', 'brief' => '', 'keyword' => '荀子,正论'],
    '19' => ['code' => '19', 'name' => '礼论', 'nameFull' => '礼论篇第十九', 'brief' => '', 'keyword' => '荀子,礼论'],
    '20' => ['code' => '20', 'name' => '乐论', 'nameFull' => '乐论篇第二十', 'brief' => '', 'keyword' => '荀子,乐论'],
    '21' => ['code' => '21', 'name' => '解蔽', 'nameFull' => '解蔽篇第二十一', 'brief' => '', 'keyword' => '荀子,解蔽'],
    '22' => ['code' => '22', 'name' => '正名', 'nameFull' => '正名篇第二十二', 'brief' => '', 'keyword' => '荀子,正名'],
    '23' => ['code' => '23', 'name' => '性恶', 'nameFull' => '性恶篇第二十三', 'brief' => '', 'keyword' => '荀子,性恶'],
    '24' => ['code' => '24', 'name' => '君子', 'nameFull' => '君子篇第二十四', 'brief' => '', 'keyword' => '荀子,君子'],
    '25' => ['code' => '25', 'name' => '成相', 'nameFull' => '成相篇第二十五', 'brief' => '', 'keyword' => '荀子,成相'],
    '26' => ['code' => '26', 'name' => '赋', 'nameFull' => '赋篇第二十六', 'brief' => '', 'keyword' => '荀子,赋'],
    '27' => ['code' => '27', 'name' => '大略', 'nameFull' => '大略篇第二十七', 'brief' => '', 'keyword' => '荀子,大略'],
    '28' => ['code' => '28', 'name' => '宥坐', 'nameFull' => '宥坐篇第二十八', 'brief' => '', 'keyword' => '荀子,宥坐'],
    '29' => ['code' => '29', 'name' => '子道', 'nameFull' => '子道篇第二十九', 'brief' => '', 'keyword' => '荀子,子道'],
    '30' => ['code' => '30', 'name' => '法行', 'nameFull' => '法行篇第三十', 'brief' => '', 'keyword' => '荀子,法行'],
    '31' => ['code' => '31', 'name' => '哀公', 'nameFull' => '哀公篇第三十一', 'brief' => '', 'keyword' => '荀子,哀公'],
    '32' => ['code' => '32', 'name' => '尧问', 'nameFull' => '尧问篇第三十二', 'brief' => '', 'keyword' => '荀子,尧问'],
];
