<?php
return [
    '1' => ['code' => '1', 'name' => '天命', 'nameFull' => '天命-第一章', 'brief' => '中和是天下的根本', 'keyword' => ''],
    '2' => ['code' => '2', 'name' => '时中', 'nameFull' => '时中-第二章', 'brief' => '君子中庸，小人反中庸', 'keyword' => ''],
    '3' => ['code' => '3', 'name' => '鲜能', 'nameFull' => '鲜能-第三章', 'brief' => '最高的道德标准', 'keyword' => ''],
    '4' => ['code' => '4', 'name' => '行明', 'nameFull' => '行明-第四章', 'brief' => '谁能食而知其味', 'keyword' => ''],
    '5' => ['code' => '5', 'name' => '不行', 'nameFull' => '不行-第五章', 'brief' => '此道也非常道', 'keyword' => ''],
    '6' => ['code' => '6', 'name' => '大知', 'nameFull' => '大知-第六章', 'brief' => '隐恶扬善，执两用中', 'keyword' => ''],
    '7' => ['code' => '7', 'name' => '予知', 'nameFull' => '予知-第七章', 'brief' => '聪明反被聪明误', 'keyword' => ''],
    '8' => ['code' => '8', 'name' => '服膺', 'nameFull' => '服膺-第八章', 'brief' => '牢牢抓住不要放弃', 'keyword' => ''],
    '9' => ['code' => '9', 'name' => '可均', 'nameFull' => '可均-第九章', 'brief' => '白刃可蹈，中庸难得', 'keyword' => ''],
    '10' => ['code' => '10', 'name' => '问强', 'nameFull' => '问强-第十章', 'brief' => '什么是真正的强？', 'keyword' => ''],
    '11' => ['code' => '11', 'name' => '素隐', 'nameFull' => '素隐-第十一章', 'brief' => '正道直行，默默无闻也不后悔', 'keyword' => ''],
    '12' => ['code' => '12', 'name' => '费隐', 'nameFull' => '费引-第十二节', 'brief' => '君子之道费而隐', 'keyword' => ''],
    '13' => ['code' => '13', 'name' => '不远', 'nameFull' => '不远-第十三章', 'brief' => '道不远人，远人非道', 'keyword' => ''],
    '14' => ['code' => '14', 'name' => '素位', 'nameFull' => '素位-第十四章', 'brief' => '素位而行，安分守己', 'keyword' => ''],
    '15' => ['code' => '15', 'name' => '行远', 'nameFull' => '行远-第十五章', 'brief' => '行远自迩，登高自卑', 'keyword' => ''],
    '16' => ['code' => '16', 'name' => '鬼神', 'nameFull' => '鬼神-第十六章', 'brief' => '无所不在的道', 'keyword' => ''],
    '17' => ['code' => '17', 'name' => '大德', 'nameFull' => '大德-第十七章', 'brief' => '天生我材必有用', 'keyword' => ''],
    '18' => ['code' => '18', 'name' => '无忧', 'nameFull' => '无忧-第十八章', 'brief' => '周公制定礼节规定', 'keyword' => ''],
    '19' => ['code' => '19', 'name' => '达孝', 'nameFull' => '达孝-第十九章', 'brief' => '真正的孝道', 'keyword' => ''],
    '20' => ['code' => '20', 'name' => '问政', 'nameFull' => '问政-第二十章', 'brief' => '治国平天下的法则', 'keyword' => ''],
    '21' => ['code' => '21', 'name' => '诚明', 'nameFull' => '诚明-第二十一章', 'brief' => '诚则明，明则诚', 'keyword' => ''],
    '22' => ['code' => '22', 'name' => '尽性', 'nameFull' => '尽性-第二十二章', 'brief' => '至诚可参天地', 'keyword' => ''],
    '23' => ['code' => '23', 'name' => '至曲', 'nameFull' => '致曲-第二十三章', 'brief' => '从一个方面下功夫', 'keyword' => ''],
    '24' => ['code' => '24', 'name' => '前知', 'nameFull' => '前知-第二十四章', 'brief' => '国家兴亡，必有征兆', 'keyword' => ''],
    '25' => ['code' => '25', 'name' => '自成', 'nameFull' => '自成-第二十五章', 'brief' => '不能只做到自我完善', 'keyword' => ''],
    '26' => ['code' => '26', 'name' => '无息', 'nameFull' => '无息-第二十六章', 'brief' => '真诚是没有止息的', 'keyword' => ''],
    '27' => ['code' => '27', 'name' => '明哲', 'nameFull' => '明哲-第二十七章', 'brief' => '明哲保身，进退自如', 'keyword' => ''],
    '28' => ['code' => '28', 'name' => '自用', 'nameFull' => '自用-第二十八章', 'brief' => '不要自以为是，独断专行', 'keyword' => ''],
    '29' => ['code' => '29', 'name' => '三重', 'nameFull' => '三重-第二十九章', 'brief' => '无征不信，不信民弗从', 'keyword' => ''],
    '30' => ['code' => '30', 'name' => '教化', 'nameFull' => '教化-第三十章', 'brief' => '圣人的伟大之处', 'keyword' => ''],
    '31' => ['code' => '31', 'name' => '至圣', 'nameFull' => '至圣-第三十一章', 'brief' => '德厚才能载物', 'keyword' => ''],
    '32' => ['code' => '32', 'name' => '至诚', 'nameFull' => '至诚-第三十二章', 'brief' => '天下唯有德者居之', 'keyword' => ''],
    '33' => ['code' => '33', 'name' => '尚纲', 'nameFull' => '尚纲-第三十三章', 'brief' => '弘扬德行的最高境界', 'keyword' => ''],
];
