<?php
return [
    'chapters' => [
        [
            'content' => [
                '若有人兮山之阿，被薜荔兮带女萝；',
                '既含睇兮又宜笑，子慕予兮善窈窕；',
                '乘赤豹兮从文狸，辛夷车兮结桂旗；',
                '被石兰兮带杜衡，折芬馨兮遗所思；',
                '余处幽篁兮终不见天，路险难兮独后来；',
                '表独立兮山之上，云容容兮而在下；',
                '杳冥冥兮羌昼晦，东风飘兮神灵雨；',
                '留灵修兮憺忘归，岁既晏兮孰华予；',
                '采三秀兮于山间，石磊磊兮葛蔓蔓；',
                '怨公子兮怅忘归，君思我兮不得闲；',
                '山中人兮芳杜若，饮石泉兮荫松柏；',
                '君思我兮然疑作；',
                '雷填填兮雨冥冥，猿啾啾兮狖夜鸣；',
                '风飒飒兮木萧萧，思公子兮徒离忧。',
            ],
            'spell' => [
                'ruò yǒu rén xī shān zhī ā, bèi bì lì xī dài nǚ luó',
                'jì hán dì xī yòu yí xiào, zi mù yǔ xī shàn yǎo tiǎo',
                'chéng chì bào xī cóng wén lí, xīn yí chē xī jié guì qí',
                'bèi shí lán xī dài dù héng, zhé fēn xīn xī yí suǒ sī',
                'yú chǔ yōu huáng xī zhōng bú jiàn tiān, lù xiǎn nán xī dú hòu lái',
                'biǎo dú lì xī shān zhī shàng, yún róng róng xī ér zài xià',
                'yǎo míng míng xī qiāng zhòu huì, dōng fēng piāo xī shén líng yǔ',
                'liú líng xiū xī dàn wàng guī, suì jì yàn xī shú huá yǔ',
                'cǎi sān xiù xī yú shān jiān, shí lěi lěi xī gé màn màn',
                'yuàn gōng zǐ xī chàng wàng guī, jūn sī wǒ xī bù dé xián',
                'shān zhōng rén xī fāng dù ruò, yǐn shí quán xī yīn sōng bǎi',
                'jūn sī wǒ xī rán yí zuò',
                'léi tián tián xī yǔ míng míng, yuán jiū jiū xī yòu yè míng',
                'fēng sà sà xī mù xiāo xiāo, sī gōng zǐ xī tú lí yōu.',
            ],
            'vernacular' => [
                '好像有个人儿在山坳，身披薜荔女萝束细腰。',
                '含情脉脉开口微微笑，你爱我啊美丽又窈窕。',
                '赤豹前拉车，后跟大花狸，辛夷木做车桂枝做旌旗。',
                '石兰做车盖杜衡做飘带，折下香花送给意中的你。',
                '我身居竹林深处暗不见天日，通路艰难险阻使我来迟。',
                '我孤独地站在高山顶端，云海茫茫在我脚下翻卷。',
                '昏昏暗暗白昼如夜晚，东风阵阵飘洒着细雨。',
                '痴心等待你不思回返，红颜已凋谢谁来顾盼？',
                '采灵芝仙草在那巫山间，山石嶙峋葛藤蔓蔓。',
                '怨恨你失约惆怅我忘返，你也思念我只是不得闲。',
                '山中人儿纯真像杜若，啜饮石泉伫立松柏下。',
                '你想我谁知是真是假。',
                '雷声隆隆细雨飘扬，长猿夜啼声声断人肠。',
                '秋风飒飒黄叶飘零，痴情思公子徒自哀伤。',
            ],
            'notes' => [
            ],
            'unscramble' => [
            ],
        ],
    ],
];
