<?php
return [
    'chapters' => [
        [
            'content' => [
                '思美人兮，揽涕而竚眙。',
                '媒绝路阻兮，言不可结而诒。',
                '蹇蹇之烦冤兮，陷滞而不发。',
                '申旦以舒中情兮，志沉菀而莫达。',
                '愿寄言于浮云兮，遇丰隆而不将。',
            ],
            'spell' => [
                'sī měi rén xī, lǎn tì ér zhù yí.',
                'méi jué lù zǔ xī, yán bù kě jié ér yí.',
                'jiǎn jiǎn zhī fán yuān xī, xiàn zhì ér bù fā.',
                'shēn dàn yǐ shū zhōng qíng xī, zhì chén wǎn ér mò dá.',
                'yuàn jì yán yú fú yún xī, yù fēng lóng ér bù jiāng.',
            ],
            'vernacular' => [
                '怀念着我心爱的人啊，揩干眼泪而远望。',
                '没人介绍而路又迢遥，有话却无法成章。',
                '我至诚一片而蒙冤，我进退两难而不前。',
                '愿每日陈述我的心思，心思沉顿而难表现。',
                '愿浮云为我捎信，云师却不肯讲情。',
            ],
        ],
        [
            'content' => [
                '因归鸟而致辞兮，羌迅高而难当。',
                '高辛之灵盛兮，遭玄鸟而致诒。',
                '欲变节以从俗兮，媿易初而屈志。',
                '独历年而离愍兮，羌凭心犹未化。',
                '宁隐闵而寿考兮，何变易之可为！',
            ],
            'spell' => [
                'yīn guī niǎo ér zhì cí xī, qiāng xùn gāo ér nán dāng.',
                'gāo xīn zhī líng shèng xī, zāo xuán niǎo ér zhì yí.',
                'yù biàn jié yǐ cóng sú xī, kuì yì chū ér qū zhì.',
                'dú lì nián ér lí mǐn xī, qiāng píng xīn yóu wèi huà.',
                'níng yǐn mǐn ér shòu kǎo xī, hé biàn yì zhī kě wèi!',
            ],
            'vernacular' => [
                '托鸿鸟为我传书，鸿高飞而不应命。',
                '我难比帝喾高辛，能遇凤凰而授卵。',
                '要变节而随流俗，我知耻而有所不敢。',
                '多年来我遭受摧残，毫不减我心中的愤懑。',
                '宁失意而长此终身，我何能如掌之易反？',
            ],
        ],
        [
            'content' => [
                '知前辙之不遂兮，未改此度。',
                '车既覆而马颠兮，蹇独怀此异路。',
                '勒骐骥而更驾兮，造父为我操之，',
                '迁逡次而勿驱兮，聊假日以须是时。',
                '指嶓冢之西隈兮，与纁黄以为期。',
            ],
            'spell' => [
                'zhī qián zhé zhī bù suí xī, wèi gǎi cǐ dù.',
                'chē jì fù ér mǎ diān xī, jiǎn dú huái cǐ yì lù.',
                'lēi qí jì ér gèng jià xī, zào fù wèi wǒ cāo zhī,',
                'qiān qūn cì ér wù qū xī, liáo jià rì yǐ xū shì shí.',
                'zhǐ bō zhǒng zhī xī wēi xī, yǔ xūn huáng yǐ wéi qī.',
            ],
            'vernacular' => [
                '我明知正路难通，但我不能不走正路。',
                '尽管是车翻而马倒，我依然望着前途。',
                '我再把好马辔上，请造父为我执鞭。',
                '慢慢地走,不必驱驰，让我把光景流连。',
                '指着嶓冢山的西边,那汉水发源地点,',
            ],
        ],
        [
            'content' => [
                '开春发岁兮，白日出之悠悠。',
                '吾将荡志而愉乐兮，遵江夏以娱忧。',
                '揽大薄之芳茝兮，搴长洲之宿莽。',
                '惜吾不及古人兮，吾谁与玩此芳草？',
                '解萹薄与杂菜兮，备以为交佩。',
            ],
            'spell' => [
                'kāi chūn fā suì xī, bái rì chū zhī yōu yōu.',
                'wú jiāng dàng zhì ér yú lè xī, zūn jiāng xià yǐ yú yōu.',
                'lǎn dà báo zhī fāng chǎi xī, qiān cháng zhōu zhī sù mǎng.',
                'xī wú bù jí gǔ rén xī, wú shuí yǔ wán cǐ fāng cǎo?',
                'jiě biǎn báo yǔ zá cài xī, bèi yǐ wéi jiāo pèi.',
            ],
            'vernacular' => [
                '就走到日落昏黄,也莫嫌道途遥远。我姑且等待明年，艳阳的春日绵绵。',
                '我要放怀地歌唱，逍遥在江水、夏水之边。',
                '我攀摘灌木中的苻蓠，我采集沙滩上的卷施。',
                '和古人可惜不能同时，摘来香草啊同谁赏识。',
                '采取萹薄与同蔬菜，尽可以纽成环佩。',
            ],
        ],
        [
            'content' => [
                '佩缤纷以缭转兮，遂萎绝而离异。',
                '吾且儃徊以娱忧兮，观南人之变态。',
                '窃快在中心兮，扬厥凭而不竢。',
                '芳与泽其杂糅兮，羌芳华自中出。',
                '纷郁郁其远蒸兮，满内而外扬。',
            ],
            'spell' => [
                'pèi bīn fēn yǐ liáo zhuǎn xī, suì wēi jué ér lí yì.',
                'wú qiě chán huái yǐ yú yōu xī, guān nán rén zhī biàn tài.',
                'qiè kuài zài zhōng xīn xī, yáng jué píng ér bù sì.',
                'fāng yǔ zé qí zá róu xī, qiāng fāng huá zì zhōng chū.',
                'fēn yù yù qí yuǎn zhēng xī, mǎn nèi ér wài yáng.',
            ],
            'vernacular' => [
                '也未尝不好看一时，终萎谢而遭毁败。',
                '我姑且快乐逍遥，观赏南方人的异态。',
                '只求我心中快活，把愤懑置之度外。',
                '芳香与污秽杂混一起啊，芳花终会卓然自现。',
                '馥郁的芳香必然远扬，内部充实外表自有辉光。',
            ],
        ],
        [
            'content' => [
                '情与质信可保兮，羌居蔽而闻章。',
                '令薜荔以为理兮，惮举趾而缘木。',
                '因芙蓉而为媒兮，惮褰裳而濡足。',
                '登高吾不说兮，入下吾不能。',
                '固朕形之不服兮，然容与而狐疑。',
                '广遂前画兮，未改此度也。',
                '命则处幽吾将罢兮，愿及白日之未暮也。',
                '独茕茕而南行兮，思彭咸之故也。',
            ],
            'spell' => [
                'qíng yǔ zhì xìn kě bǎo xī, qiāng jū bì ér wén zhāng.',
                'lìng bì lì yǐ wéi lǐ xī, dàn jǔ zhǐ ér yuán mù.',
                'yīn fú róng ér wèi méi xī, dàn qiān shang ér rú zú.',
                'dēng gāo wú bù shuō xī, rù xià wú bù néng.',
                'gù zhèn xíng zhī bù fú xī, rán róng yǔ ér hú yí.',
                'guǎng suì qián huà xī, wèi gǎi cǐ dù yě.',
                'mìng zé chù yōu wú jiāng bà xī, yuàn jí bái rì zhī wèi mù yě.',
                'dú qióng qióng ér nán xíng xī, sī péng xián zhī gù yě.',
            ],
            'vernacular' => [
                '只要真诚的素质长保不亡，声名会突破一切的阻障。',
                '想请薜荔替我说合，又怕走路去攀上树枝。',
                '想采荷花替我媒介，又怕下水打湿了裙子。',
                '登高吧,我不高兴，下水吧,我也不能。',
                '固然是我手足不惯。我犹豫而心不能定。',
                '完全依照着旧贯，我始终不肯改变。',
                '命该受难我也不管，趁着这日子还未过完。',
                '一个人孤单地走向南边，只想追求彭咸的典范。',
            ],
            'notes' => [
            ],
        ],
    ],
    'unscramble' => [
    ],
];
